### ISSUE TITLE
同一个vps中接入ssp和v2b,无法使用

### ISSUE THREAD

**Issue by victoryLV** [ColetteContreras/v2ray-poseidon#102]
同一个vps中接入ssp和v2b,没有任何报错，sspanel使用正常，但是v2b无法使用；
![image](https://user-images.githubusercontent.com/32597550/111865637-28ac7f00-89a3-11eb-97f7-c02c1178f7c5.png)

**Comment by zhouchiyan82** [comment]
是的我也遇到这个问题

**Comment by ColetteContreras** [comment]
由于 v2b 默认将后端的日志给关闭了，所以需要在 v2b 后台先打开后端日志，才能知道是什么错误。
