### ISSUE TITLE
能否同一vps多用户配置

### ISSUE THREAD

**Issue by evan8623** [ColetteContreras/v2ray-poseidon#103]
作者好，想问一下在同一个vps上，配置文件能否写多个"nodeId"，实现多个节点？比如前端1节点没有限速，2节点设置限速，能否在配置文件上写多个配置实现？

**Comment by ColetteContreras** [comment]
这属于多开的范畴

使用 systemd 部署多开教程 https://poseidon-gfw.cc/za-xiang/run-multi-instance-of-v2ray-poseidon 
使用 docker 部署多开教程 https://poseidon-gfw.cc/za-xiang/run-multi-instance-of-v2ray-poseidon-with-docker
