### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by Code-CJ** [ColetteContreras/v2ray-poseidon#108]
Centos 7 前后端独立 表现情况为 前端节点 一直是红色 
后端docker-compose logs 报错 （最后一栏）
以下是日志
Attaching to v2ray-ws-tls
v2ray-ws-tls    | v2ray -config /etc/v2ray/config.json
v2ray-ws-tls    | V2Ray-Poseidon v2.2.0 (Xray-core: 1.4.2)
v2ray-ws-tls    | env[CERT_FILE]=
v2ray-ws-tls    | env[KEY_FILE]=
v2ray-ws-tls    | env[CERT_MODE]=dns
v2ray-ws-tls    | run command: /root/.acme.sh/acme.sh --version
v2ray-ws-tls    | run command: /bin/sh -c curl https://get.acme.sh | sh
v2ray-ws-tls    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
v2ray-ws-tls    |                                  Dload  Upload   Total   Spent    Left  Speed
100   937    0   937    0     0   4203      0 --:--:-- --:--:-- --:--:--  4220
v2ray-ws-tls    |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
v2ray-ws-tls    |                                  Dload  Upload   Total   Spent    Left  Speed
100  203k  100  203k    0     0  5596k      0 --:--:-- --:--:-- --:--:-- 5645k
v2ray-ws-tls    | [Sat Sep  4 06:50:01 CST 2021] Installing from online archive.
v2ray-ws-tls    | [Sat Sep  4 06:50:01 CST 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
v2ray-ws-tls    | [Sat Sep  4 06:50:01 CST 2021] Extracting master.tar.gz
v2ray-ws-tls    | [Sat Sep  4 06:50:01 CST 2021] Installing to /root/.acme.sh
v2ray-ws-tls    | [Sat Sep  4 06:50:01 CST 2021] Installed to /root/.acme.sh/acme.sh
v2ray-ws-tls    | [Sat Sep  4 06:50:01 CST 2021] No profile is found, you will need to go into /root/.acme.sh to use acme.sh
v2ray-ws-tls    | [Sat Sep  4 06:50:01 CST 2021] Installing cron job
v2ray-ws-tls    | [Sat Sep  4 06:50:02 CST 2021] Good, bash is found, so change the shebang to use bash as preferred.
v2ray-ws-tls    | [Sat Sep  4 06:50:02 CST 2021] OK
v2ray-ws-tls    | [Sat Sep  4 06:50:02 CST 2021] Install success!
v2ray-ws-tls    | env[CERT_DOMAIN]=jp2.xxxx.xxxx
v2ray-ws-tls    | env[DNS_PROVIDER]=dns_cf
v2ray-ws-tls    | run command: /root/.acme.sh/acme.sh --issue -d jp2.xxxx.xxxx --dns dns_cf -m my@example.com
v2ray-ws-tls    | [Sat Sep  4 06:50:04 CST 2021] Using CA: https://acme.zerossl.com/v2/DV90
v2ray-ws-tls    | [Sat Sep  4 06:50:04 CST 2021] Create account key ok.
v2ray-ws-tls    | [Sat Sep  4 06:50:04 CST 2021] No EAB credentials found for ZeroSSL, let's get one
v2ray-ws-tls    | [Sat Sep  4 06:50:05 CST 2021] Registering account: https://acme.zerossl.com/v2/DV90
v2ray-ws-tls    | [Sat Sep  4 06:50:07 CST 2021] Registered
v2ray-ws-tls    | [Sat Sep  4 06:50:07 CST 2021] ACCOUNT_THUMBPRINT='yP4V-aZuNJyVkrfM7vOwseVRzNkmRoex2c9xl4DAqp0'
v2ray-ws-tls    | [Sat Sep  4 06:50:08 CST 2021] Creating domain key
v2ray-ws-tls    | [Sat Sep  4 06:50:08 CST 2021] The domain key is here: /root/.acme.sh/jp2.xxxx.xxxx/jp2.xxxx.xxxx.key
v2ray-ws-tls    | [Sat Sep  4 06:50:08 CST 2021] Single domain='jp2.xxxx.xxxx'
v2ray-ws-tls    | [Sat Sep  4 06:50:08 CST 2021] Getting domain auth token for each domain
v2ray-ws-tls    | [Sat Sep  4 06:50:10 CST 2021] Getting webroot for domain='jp2.xxxx.xxxx'
v2ray-ws-tls    | [Sat Sep  4 06:50:11 CST 2021] Adding txt value: s4QLnxYlDtLKeTVW8zIhz52gEOBd5TPo0n3vykAo-lU for domain:  _acme-challenge.jp2.xxxx.xxxx
v2ray-ws-tls    | [Sat Sep  4 06:50:15 CST 2021] Adding record
v2ray-ws-tls    | [Sat Sep  4 06:50:15 CST 2021] Added, OK
v2ray-ws-tls    | [Sat Sep  4 06:50:15 CST 2021] The txt record is added: Success.
v2ray-ws-tls    | [Sat Sep  4 06:50:15 CST 2021] Let's check each DNS record now. Sleep 20 seconds first.
v2ray-ws-tls    | [Sat Sep  4 06:50:35 CST 2021] You can use '--dnssleep' to disable public dns checks.
v2ray-ws-tls    | [Sat Sep  4 06:50:35 CST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/dnscheck
v2ray-ws-tls    | [Sat Sep  4 06:50:36 CST 2021] Checking jp2.xxxx.xxxx for _acme-challenge.jp2.xxxx.xxxx
v2ray-ws-tls    | [Sat Sep  4 06:50:36 CST 2021] Domain jp2.xxxx.xxxx '_acme-challenge.jp2.xxxx.xxxx' success.
v2ray-ws-tls    | [Sat Sep  4 06:50:36 CST 2021] All success, let's return
v2ray-ws-tls    | [Sat Sep  4 06:50:36 CST 2021] Verifying: jp2.xxxx.xxxx
v2ray-ws-tls    | [Sat Sep  4 06:50:37 CST 2021] Processing, The CA is processing your order, please just wait. (1/30)
v2ray-ws-tls    | [Sat Sep  4 06:50:40 CST 2021] Success
v2ray-ws-tls    | [Sat Sep  4 06:50:40 CST 2021] Removing DNS records.
v2ray-ws-tls    | [Sat Sep  4 06:50:40 CST 2021] Removing txt: s4QLnxYlDtLKeTVW8zIhz52gEOBd5TPo0n3vykAo-lU for domain: _acme-challenge.jp2.xxxx.xxxx
v2ray-ws-tls    | [Sat Sep  4 06:50:41 CST 2021] Removed: Success
v2ray-ws-tls    | [Sat Sep  4 06:50:41 CST 2021] Verify finished, start to sign.
v2ray-ws-tls    | [Sat Sep  4 06:50:41 CST 2021] Lets finalize the order.
v2ray-ws-tls    | [Sat Sep  4 06:50:41 CST 2021] Le_OrderFinalize='https://acme.zerossl.com/v2/DV90/order/7V7r1uQZ4LfyqzldhJTEtQ/finalize'
v2ray-ws-tls    | [Sat Sep  4 06:50:42 CST 2021] Order status is processing, lets sleep and retry.
v2ray-ws-tls    | [Sat Sep  4 06:50:42 CST 2021] Retry after: 15
v2ray-ws-tls    | [Sat Sep  4 06:50:57 CST 2021] Polling order status: https://acme.zerossl.com/v2/DV90/order/7V7r1uQZ4LfyqzldhJTEtQ
v2ray-ws-tls    | [Sat Sep  4 06:50:58 CST 2021] Downloading cert.
v2ray-ws-tls    | [Sat Sep  4 06:50:58 CST 2021] Le_LinkCert='https://acme.zerossl.com/v2/DV90/cert/2ZPVJteEmX-Tz8v8DSPbSQ'
v2ray-ws-tls    | [Sat Sep  4 06:51:00 CST 2021] Cert success.
v2ray-ws-tls    | -----BEGIN CERTIFICATE-----
v2ray-ws-tls    | MIIGcTCCBFmgAwIBAgIRAOoj6pGGg+R3ttqRU39BE7owDQYJKoZIhvcNAQEMBQAw
v2ray-ws-tls    | SzELMAkGA1UEBhMCQVQxEDAOBgNVBAoTB1plcm9TU0wxKjAoBgNVBAMTIVplcm9T
v2ray-ws-tls    | U0wgUlNBIERvbWFpbiBTZWN1cmUgU2l0ZSBDQTAeFw0yMTA5MDMwMDAwMDBaFw0y
v2ray-ws-tls    | MTEyMDIyMzU5NTlaMBwxGjAYBgNVBAMTEWpwMi5wcGFwMjAxNy5jbHViMIIBIjAN
v2ray-ws-tls    | BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyzY+Auim8Fnkw0we7mVwGC8cNBzs
v2ray-ws-tls    | KCJqxdZHdFWooxDPbVEchq50H8kNGYu0e68Eo67gltFL2Jf3yVJHXxuhTvHKnolJ
v2ray-ws-tls    | 5tHpmAa2lAvwVTZ1h+Wv1jrliyVFDwDESv64yG3+3fo/vW/fTCSXwXyT8yKnAsop
v2ray-ws-tls    | gmTxWXQPfJI77kmkOICF/j6kqJH1VdcyCTeON3L1LzfmoFGElFyR0cOx3ydVIKWZ
v2ray-ws-tls    | FA1VOzvJ3xkm/1PbFaEUrUVBP2kZ3vvzmzyI3r8WRlE2aSKfa9AWZ9CAn+V2oT9u
v2ray-ws-tls    | WqTZioRTBLu6m+J1gEGP9Sc+B+RJ5QB7cwCLzswvAppjdd710dBMKfVeCQIDAQAB
v2ray-ws-tls    | o4ICfTCCAnkwHwYDVR0jBBgwFoAUyNl4aKLZGWjVPXLeXwo+3LWGhqYwHQYDVR0O
v2ray-ws-tls    | BBYEFEUvRK3WMT3xJjywsYX7VCiSpCegMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMB
v2ray-ws-tls    | Af8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBJBgNVHSAEQjBA
v2ray-ws-tls    | MDQGCysGAQQBsjEBAgJOMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5j
v2ray-ws-tls    | b20vQ1BTMAgGBmeBDAECATCBiAYIKwYBBQUHAQEEfDB6MEsGCCsGAQUFBzAChj9o
v2ray-ws-tls    | dHRwOi8vemVyb3NzbC5jcnQuc2VjdGlnby5jb20vWmVyb1NTTFJTQURvbWFpblNl
v2ray-ws-tls    | Y3VyZVNpdGVDQS5jcnQwKwYIKwYBBQUHMAGGH2h0dHA6Ly96ZXJvc3NsLm9jc3Au
v2ray-ws-tls    | c2VjdGlnby5jb20wggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdQB9PvL4j/+IVWgk
v2ray-ws-tls    | wsDKnlKJeSvFDngJfy5ql2iZfiLw1wAAAXut22smAAAEAwBGMEQCIAssJ5eErOZK
v2ray-ws-tls    | UHCfBguEayKxYHRN4n88RNvHwU6NCWhcAiABgCJ/oU3f9HC+8VXCiPRonVxa10DG
v2ray-ws-tls    | GmC2WAW+vY9T1wB3AESUZS6w7s6vxEAH2Kj+KMDa5oK+2MsxtT/TM5a1toGoAAAB
v2ray-ws-tls    | e63bavcAAAQDAEgwRgIhAOxJDO/W/my9JBeLPasH3z0g4QtHHZ9pu57GyWXPg2w5
v2ray-ws-tls    | AiEAve36O+PoyGJTSZxeEgxRCynjEh5QrJr7fgDIFnA9vEgwHAYDVR0RBBUwE4IR
v2ray-ws-tls    | anAyLnBwYXAyMDE3LmNsdWIwDQYJKoZIhvcNAQEMBQADggIBACdImzFQPhGvv1M9
v2ray-ws-tls    | tgN2H4gBTJpZgMajVbu8wfs/FL+xx3zq0EOU6q6QOyAceZH1VhmVps61dRnbrswF
v2ray-ws-tls    | VXSZh7gPYGqbPEOt8wdHPW2SdRvK7HB853eK9zVPVxi5n0Cme15IZHIVFMt3k0u6
v2ray-ws-tls    | uFHFiMDwWsec80gutN9MFWnrChqc18hwlzZon24Yn+b37WiYUWn4uKaWwvMge9Bv
v2ray-ws-tls    | xau98G09Lfe9DzK6GwNxED3+TS2Z97F7Fho88Oh8+/tl/sTTCT0w2il+TYiOywix
v2ray-ws-tls    | Ga1L1yzKQb6TzicGf9mXfIZnET4LROeirr/yqc5eVCAPfov9QfcMtbvrWdKkgw/+
v2ray-ws-tls    | BKjtxnQREblfWIGCaPtFbPOmQZrKzPLoZs64h8kY7TS0imiAv1m1NPAYL3axhWvr
v2ray-ws-tls    | SbnvZeSdKQt8wcT1DAfm2L42ohfdHpFcLOftrz6f86JA4DoeEqZtdWsGjCCw+erd
v2ray-ws-tls    | WJdX5roiqhXtFrzJFOec+YzmMaBRUv8QE9nzmvTlpcss6a4ryYTMJH/Wu+DDxh//
v2ray-ws-tls    | Z26ThzepfVJIXmTQDYP5ZqevCUdXFdNLf0ORY+sJ7H+o99XMg5+Xas3lCrWVI/US
v2ray-ws-tls    | MNeVg1jlVBByCpGjL1t58dWr1NAvxW4V/QfoVsXctrO10nc9U54QRzk9yoFSaLoi
v2ray-ws-tls    | El0waML/Fa85zoLo06y39j74Ec1X
v2ray-ws-tls    | -----END CERTIFICATE-----
v2ray-ws-tls    | [Sat Sep  4 06:51:00 CST 2021] Your cert is in: /root/.acme.sh/jp2.xxxx.xxxx/jp2.xxxx.xxxx.cer
v2ray-ws-tls    | [Sat Sep  4 06:51:00 CST 2021] Your cert key is in: /root/.acme.sh/jp2.xxxx.xxxx/jp2.xxxx.xxxx.key
v2ray-ws-tls    | [Sat Sep  4 06:51:00 CST 2021] The intermediate CA cert is in: /root/.acme.sh/jp2.xxxx.xxxx/ca.cer
v2ray-ws-tls    | [Sat Sep  4 06:51:00 CST 2021] And the full chain certs is there: /root/.acme.sh/jp2.xxxx.xxxx/fullchain.cer
v2ray-ws-tls    | run command: /root/.acme.sh/acme.sh --installcert -d jp2.xxxx.xxxx --fullchainpath /etc/v2ray/v2ray.crt --keypath /etc/v2ray/v2ray.key
v2ray-ws-tls    | [Sat Sep  4 06:51:00 CST 2021] Installing key to: /etc/v2ray/v2ray.key
v2ray-ws-tls    | [Sat Sep  4 06:51:00 CST 2021] Installing full chain to: /etc/v2ray/v2ray.crt
v2ray-ws-tls    | 2021/09/04 06:51:00 [Info] V2ray-Poseidon: updating geoip.dat and geosite.dat
v2ray-ws-tls    | 2021/09/04 06:51:00 [Warning] V2ray-Poseidon: panel: V2board
v2ray-ws-tls    | 2021/09/04 06:51:00 [Warning] V2ray-Poseidon: node > check interval 60s
v2ray-ws-tls    | 2021/09/04 06:51:00 [Warning] V2ray-Poseidon: node > speed limit unlimited
v2ray-ws-tls    | 2021/09/04 06:51:00 [Warning] V2ray-Poseidon: user > max online ip count 0
v2ray-ws-tls    | 2021/09/04 06:51:00 [Warning] V2ray-Poseidon: user > speed limit unlimited
v2ray-ws-tls    | 2021/09/04 06:51:00 [Error] V2ray-Poseidon: fetch v2ray config error: http get > Get "jp1.xxxx.xxxx/api/v1/server/poseidon/config?local_port=39451&node_id=1&poseidon_version=v2.2.0&token=K7SSzx81uNS6j1YK": unsupported protocol scheme ""
v2ray-ws-tls    | v2ray -config /etc/v2ray/config.json
v2ray-ws-tls    | V2Ray-Poseidon v2.2.0 (Xray-core: 1.4.2)
v2ray-ws-tls    | env[CERT_FILE]=
v2ray-ws-tls    | env[KEY_FILE]=
v2ray-ws-tls    | env[CERT_MODE]=dns
v2ray-ws-tls    | run command: /root/.acme.sh/acme.sh --version
v2ray-ws-tls    | https://github.com/acmesh-official/acme.sh
v2ray-ws-tls    | v3.0.1
v2ray-ws-tls    | env[CERT_DOMAIN]=jp2.xxxx.xxxx
v2ray-ws-tls    | env[DNS_PROVIDER]=dns_cf
v2ray-ws-tls    | run command: /root/.acme.sh/acme.sh --issue -d jp2.xxxx.xxxx --dns dns_cf -m my@example.com
v2ray-ws-tls    | [Sat Sep  4 07:33:00 CST 2021] Domains not changed.
v2ray-ws-tls    | [Sat Sep  4 07:33:00 CST 2021] Skip, Next renewal time is: Tue Nov  2 22:51:00 UTC 2021
v2ray-ws-tls    | [Sat Sep  4 07:33:00 CST 2021] Add '--force' to force to renew.
v2ray-ws-tls    | run command: /root/.acme.sh/acme.sh --installcert -d jp2.xxxx.xxxx --fullchainpath /etc/v2ray/v2ray.crt --keypath /etc/v2ray/v2ray.key
v2ray-ws-tls    | [Sat Sep  4 07:33:00 CST 2021] Installing key to: /etc/v2ray/v2ray.key
v2ray-ws-tls    | [Sat Sep  4 07:33:00 CST 2021] Installing full chain to: /etc/v2ray/v2ray.crt
v2ray-ws-tls    | 2021/09/04 07:33:00 [Info] V2ray-Poseidon: geoip.dat updated at 2021-09-04 06:51:00.534310752 +0800 CST
v2ray-ws-tls    | 2021/09/04 07:33:00 [Info] V2ray-Poseidon: geosite.dat updated at 2021-09-04 06:51:00.561310273 +0800 CST
v2ray-ws-tls    | 2021/09/04 07:33:00 [Warning] V2ray-Poseidon: panel: V2board
v2ray-ws-tls    | 2021/09/04 07:33:00 [Warning] V2ray-Poseidon: node > check interval 60s
v2ray-ws-tls    | 2021/09/04 07:33:00 [Warning] V2ray-Poseidon: node > speed limit unlimited
v2ray-ws-tls    | 2021/09/04 07:33:00 [Warning] V2ray-Poseidon: user > max online ip count 0
v2ray-ws-tls    | 2021/09/04 07:33:00 [Warning] V2ray-Poseidon: user > speed limit unlimited
v2ray-ws-tls    | 2021/09/04 07:33:00 [Error] V2ray-Poseidon: fetch v2ray config error: http get > Get "jp1.xxxx.xxxx/api/v1/server/poseidon/config?local_port=34389&node_id=3&poseidon_version=v2.2.0&token=K7SSzx81uNS6j1YK": unsupported protocol scheme ""

**Comment by lawshon** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
