### ISSUE TITLE
希望增加V2Board的nginx(caddy)+ws+tls教程

### ISSUE THREAD

**Issue by Topcckin** [ColetteContreras/v2ray-poseidon#36]
面板：V2Board
按照Wiki 《0301 v2board v2rayposeidon ws tls教程》后端对接V2Board成功，能够正常上网。
进一步准备使用nginx+ws+tls时，一直失败，sspanel与ssrpanel都有详细教程，所以希望大佬能够出一个V2Board的nginx（caddy）+ws+tls教程.再次感谢大佬。

**Comment by ColetteContreras** [comment]
> 进一步准备使用nginx+ws+tls时，一直失败

为什么要单独使用 nginx ? 如果是单独使用 nginx 的话应该使用 ws 版的，这样证书需要在 nginx 这一层去配置。

> 所以希望大佬能够出一个V2Board的nginx（caddy）+ws+tls教程

请参阅[《0201 对接 V2board 教程》](https://github.com/ColetteContreras/v2ray-poseidon/wiki/0201-%E5%AF%B9%E6%8E%A5-V2board-%E6%95%99%E7%A8%8B)，应该能满足你的需求

<img width="722" alt="Snap 2020-02-10 at 12 03 19 PM" src="https://user-images.githubusercontent.com/45476574/74120171-57332480-4bfd-11ea-9c74-c3e430eb41aa.png">

**Comment by Topcckin** [comment]
先回答一下，我比较喜欢使用nginx分流配合v2ray使用，只从nginx配置证书，亲测订阅可用，有一个问题就是，生成的订阅没有自动勾选上tls，不过这应该是面板上的问题，等会去v2board面板提个Issues试试，感谢大佬回答，谢谢。
