### ISSUE TITLE
v2ray.service 無法啟動

### ISSUE THREAD

**Issue by PoorerImmune** [ColetteContreras/v2ray-poseidon#37]
我用的是 Debian 10 系統，按照 wiki 的說明對接 V2Board 的後端。但是對接了一天，就是啟動不了 V2Ray 服務，不知道哪裡出了問題。我已經照著說明文件修改了 config.json，內容如下：

```
{
  "poseidon": {
    "panel": "v2board",
    "nodeId": 1,
    "license_key": "",
    "checkRate": 60,
    "webapi": "https://xxxxxxx.com",
    "token": "N97ywHrKdf3RN2qQ",
    "localPort": 1026
  }
}
```

並且我已經為該組態檔中的域名申請了 SSL 憑證，並將其放置在 /home/v2ray.cer 和 /home/v2ray.key。可是 v2ray.service 總是啟動失敗，內容如下：

```
v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-02-11 22:30:12 CST; 40s ago
  Process: 2193 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, sta
 Main PID: 2193 (code=exited, status=203/EXEC)

 2月 11 22:30:12 ProxyServer systemd[1]: v2ray.service: Main process exited, code=exited, statu
 2月 11 22:30:12 ProxyServer systemd[1]: v2ray.service: Failed with result 'exit-code'.
 2月 11 22:30:12 ProxyServer systemd[1]: v2ray.service: Service RestartSec=100ms expired, sched
 2月 11 22:30:12 ProxyServer systemd[1]: v2ray.service: Scheduled restart job, restart counter 
 2月 11 22:30:12 ProxyServer systemd[1]: Stopped V2Ray Service.
 2月 11 22:30:12 ProxyServer systemd[1]: v2ray.service: Start request repeated too quickly.
 2月 11 22:30:12 ProxyServer systemd[1]: v2ray.service: Failed with result 'exit-code'.
 2月 11 22:30:12 ProxyServer systemd[1]: Failed to start V2Ray Service.
```

**Comment by ColetteContreras** [comment]
这个错了/home/v2ray.cer，需要  /home/v2ray.crt ，你根据相应的格式转换一下

然后手动运行 v2ray，并把所有的输出内容粘贴过来。

```
/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json ; cat access.log error.log
```

**Comment by PoorerImmune** [comment]
出現了新的問題。在執行「/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json」時出現如下錯誤：
```
V2ray-Poseidon: fetch v2ray config error: http get > status 404 body is not json, 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Not Found</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .code {
                border-right: 2px solid;
                font-size: 26px;
                padding: 0 15px 0 15px;
                text-align: center;
            }

            .message {
                font-size: 18px;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="code">
                404            </div>

            <div class="message" style="padding: 10px;">
                Not Found            </div>
        </div>
    </body>
</html>
```
使用「curl "https://xxxxxxx.com.com/api/v1/server/poseidon/config?local_port=1026&node_id=1&token=N97ywHrKdf3RN2qQ"」時結果同上。

**Comment by PoorerImmune** [comment]
出現了新的問題。在執行「/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json」時出現如下錯誤：
```
V2ray-Poseidon: fetch v2ray config error: http get > status 404 body is not json, 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Not Found</title>

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .code {
                border-right: 2px solid;
                font-size: 26px;
                padding: 0 15px 0 15px;
                text-align: center;
            }

            .message {
                font-size: 18px;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="code">
                404            </div>

            <div class="message" style="padding: 10px;">
                Not Found            </div>
        </div>
    </body>
</html>
```
使用「curl "https://xxxxxxx.com.com/api/v1/server/poseidon/config?local_port=1026&node_id=1&token=N97ywHrKdf3RN2qQ"」時結果同上。

**Comment by ColetteContreras** [comment]
新版后端需要用新版 v2board

**Comment by PoorerImmune** [comment]
@ColetteContreras 那這個版本的 V2board 需要配合使用哪個版本的後端呢？

**Comment by ColetteContreras** [comment]
@PoorerImmune 先把面板弄好吧，再来弄后端

**Comment by PoorerImmune** [comment]
弄好前端還是無效。v2ray.service 啟動數秒後便會停止。Journalctl 給出的執行記錄如下：
```
 3月 05 00:02:14 ProxyServer systemd[1]: Started V2Ray Service.
 3月 05 00:02:15 ProxyServer v2ray[8028]: V2Ray-Poseidon v1.3.2 (core: 4.21.2)
 3月 05 00:02:15 ProxyServer v2ray[8028]: 2020/03/05 00:02:15 [Warning] V2ray-Poseidon: panel: V2board
 3月 05 00:02:15 ProxyServer v2ray[8028]: 2020/03/05 00:02:15 [Warning] V2ray-Poseidon: node > check interval 60s
 3月 05 00:02:15 ProxyServer v2ray[8028]: 2020/03/05 00:02:15 [Warning] V2ray-Poseidon: node > speed limit unlimited
 3月 05 00:02:15 ProxyServer v2ray[8028]: 2020/03/05 00:02:15 [Warning] V2ray-Poseidon: user > max online ip count 0
 3月 05 00:02:15 ProxyServer v2ray[8028]: 2020/03/05 00:02:15 [Warning] V2ray-Poseidon: user > speed limit unlimited
 3月 05 00:02:16 ProxyServer systemd[1]: v2ray.service: Main process exited, code=exited, status=254/n/a
 3月 05 00:02:16 ProxyServer systemd[1]: v2ray.service: Failed with result 'exit-code'.
 3月 05 00:02:16 ProxyServer systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
 3月 05 00:02:16 ProxyServer systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
 3月 05 00:02:16 ProxyServer systemd[1]: Stopped V2Ray Service.
 3月 05 00:02:16 ProxyServer systemd[1]: v2ray.service: Start request repeated too quickly.
 3月 05 00:02:16 ProxyServer systemd[1]: v2ray.service: Failed with result 'exit-code'.
 3月 05 00:02:16 ProxyServer systemd[1]: Failed to start V2Ray Service.
```
前端的版本已更新到 1.1.2,。

**Comment by thank243** [comment]
真是菜的抠脚，心疼大佬一秒。这种issue小弟都是直接close。

**Comment by ColetteContreras** [comment]
日志
```
cat /access.log /error.log
```

后端版本？

**Comment by ColetteContreras** [comment]
@thank243 怎么说呢，总比在群里的那些人还是要好，知道提 issue

**Comment by thank243** [comment]
直接用命令运行会么？
/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

**Comment by PoorerImmune** [comment]
> 日志
> 
> ```
> cat /access.log /error.log
> ```
> 
> 后端版本？

我該提供的在前面都已經提供了。Journalctl 中寫得很清楚，後端版本是 1.3.2，v2ray 的核心版本為 4.21.2。另外，我的系統上並沒有產生 V2Ray 的日誌。根目錄下沒有 access.log 和 error.log，/var/log/v2ray 目錄中也是空白。我不清楚該腳本是否對 Linux 發行版有要求。

**Comment by PoorerImmune** [comment]
> 直接用命令运行会么？
> /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

注意審題，把前文認真看一遍。

**Comment by thank243** [comment]
> > 直接用命令运行会么？
> > /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
> 
> 注意審題，兄弟，你把前文認真看一遍再來說話。
> 我提出了這個問題，會有同樣的人再次遇到的。Github 上的 issue 就是一個知識庫，如果這個問題能夠得到解決，那別人在這裡搜一搜，不是可以少走很多彎路嗎？作者也可以參照 issue 來完善官方文檔，反思一下是不是有些細節需要加以補充。你為什麼就不這麼想呢？還直接把 issue 關了？

debug 模式都不会开，怎么看。估计你下个回复马上就是debug怎么开，我用的是v2b。

**Comment by PoorerImmune** [comment]
後端問題無法解決，遂關閉。

**Comment by thank243** [comment]
一言不合就关闭。大概率v2b下发的配置文件有问题。如果这样，

**Comment by PoorerImmune** [comment]
折騰了一個多星期，發現是前端有一項模棱兩可的設定造成誤導，修改為如圖所示之後，v2ray.service 啟動成功：

![註解 2020-03-07 200807](https://user-images.githubusercontent.com/48857142/76166308-8f943700-6198-11ea-8459-fbd0fc25c23f.png)

對於連結所用的連接埠和服務所用的連接埠，我一開始都填入的是 443，後來將其改成兩個不同的值後終於將服務啟動成功了。

我就不明白了：
① 服務所用的連接埠和我在 config.json 中所填的連接埠 1025 有什麼區別嗎？
② 我要如何判斷我的 VPS 採用的是不是 NAT 網路呢？

**我估計 Telegram 群組裡和我一樣碰到這個問題的人十有八九是栽到了這個坑裡！**

**Comment by thank243** [comment]
我猜你后端一定是nginx或者caddy作为反代。这样就可以解释443 为什么启动不了。如果你外网可以直接访问到你服务器443端口，基本上刘不会是nat主机。

**Comment by jinastaka** [comment]
_port=10084&node_id=1&token=ZJZ3IQ1XWER2kYTaFkfyYv-cZQaII90DLXNyzKyU: dial tcp xx.xx.xx.44:443: connect: connection refused  提示这个，有什么办法

**Comment by thank243** [comment]
> _port=10084&node_id=1&token=ZJZ3IQ1XWER2kYTaFkfyYv-cZQaII90DLXNyzKyU: dial tcp xx.xx.xx.44:443: connect: connection refused 提示这个，是什么原因

大概率443端口被墙了，请使用port.ping.pe检测下

**Comment by jinastaka** [comment]
port.ping.pe检测正常，只中国联通不通，

**Comment by jinastaka** [comment]
难道我配置不对？

**Comment by PoorerImmune** [comment]
> _port=10084&node_id=1&token=ZJZ3IQ1XWER2kYTaFkfyYv-cZQaII90DLXNyzKyU: dial tcp xx.xx.xx.44:443: connect: connection refused 提示这个，是什么原因

你的前端面板和後端節點部署在同一台機器上嗎？

**Comment by jinastaka** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PoorerImmune"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上9:43
收件人:&nbsp;"ColetteContreras/v2ray-poseidon"<v2ray-poseidon@noreply.github.com&gt;;
抄送:&nbsp;"鹰"<1842962557@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ColetteContreras/v2ray-poseidon] v2ray.service 無法啟動 (#37)





  
_port=10084&amp;node_id=1&amp;token=ZJZ3IQ1XWER2kYTaFkfyYv-cZQaII90DLXNyzKyU: dial tcp xx.xx.xx.44:443: connect: connection refused 提示这个，是什么原因
  
你的前端面板和後端節點部署在同一台機器上嗎？

**Comment by PoorerImmune** [comment]
> 是的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"PoorerImmune"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月16日(星期一) 晚上9:43 收件人:&nbsp;"ColetteContreras/v2ray-poseidon"<v2ray-poseidon@noreply.github.com&gt;; 抄送:&nbsp;"鹰"<1842962557@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [ColetteContreras/v2ray-poseidon] v2ray.service 無法啟動 (#37) _port=10084&amp;node_id=1&amp;token=ZJZ3IQ1XWER2kYTaFkfyYv-cZQaII90DLXNyzKyU: dial tcp xx.xx.xx.44:443: connect: connection refused 提示这个，是什么原因 你的前端面板和後端節點部署在同一台機器上嗎？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你是不是照著圖片改了兩個連接埠就完事了？

**Comment by jinastaka** [comment]
PoorerImmune  你的回答，一针见血。。。。。我启动了ws-tls面板就进不去了

**Comment by jinastaka** [comment]
PoorerImmune  能不能教教我，方便的话加下q，

**Comment by PoorerImmune** [comment]
> PoorerImmune 你的回答，一针见血。。。。。我启动了ws-tls面板就进不去了

這個問題我要好好回答一下，因為我也是自己摸索了一個多星期才搞明白 V2Board。問了兩個作者，他倆要麼不作聲，要麼答非所問。我稍後回覆你。

**Comment by jinastaka** [comment]
PoorerImmune  请不吝赐教，我也摸索2个多星期了，开始弄面板反复进不去，后来问了半天才知道 教程上的伪静态错误。。最近一个礼拜研究对接。。。这个问题那个问题，昨天看到这里解决了一个问题，然后今天是连接拒绝 @

**Comment by jinastaka** [comment]
@ @PoorerImmune，方便的加下q

**Comment by PoorerImmune** [comment]
> PoorerImmune 你的回答，一针见血。。。。。我启动了ws-tls面板就进不去了

如果前後端部署在一台機器上的話，你要注意連接埠佔用的問題，主要是 443 連接埠。

官方文檔推薦的是 aapanel，對應的中文版就是「寶塔」，它本身不佔用 443 連接埠，預設佔用 8888 連接埠。佔用 443 連接埠的主要是給前端面板 V2Board 提供服務的 Nginx。

這裡有一個細節：V2Board 本身有一項設定讓你決定要不要使用 TLS。請注意，這裡的 TLS 設定是直接針對 v2ray.service 本身的，假如你的某個後端節點部署在機器 B 上，而你的寶塔面板、Nginx 和 V2Board 部署在機器 A 上，這個時候節點的 TLS 連線不依賴 Nginx，所以需要 v2ray.service 本身自帶 SSL 憑證，故你需要在 v2ray-poseidon 的組態 config.json 中指定 SSL 憑證的存放位置，並在 V2Board 中將「TLS」設為「支持」。由於我們的前後端部署在同一台機器 A 上，故 v2ray.service 所需要的 SSL 憑證就應該在 Nginx 這一層面去部署，不需要在 config.json 中指定 SSL 憑證的位置，並且要將 V2Board 中的「TLS」設為「不支持」。

![image](https://user-images.githubusercontent.com/48857142/76765753-e1a90e00-67d1-11ea-873f-22322ca75c62.png)

由於我們希望 V2Ray 走 443 連接埠，所以將「連接端口」設為 443：

![image](https://user-images.githubusercontent.com/48857142/76766914-bb846d80-67d3-11ea-8d76-17ae55d1209f.png)

又由於 Nginx 已經佔用了 443，所以我們將「服務端口」設為其它的值，例如 4433：

![image](https://user-images.githubusercontent.com/48857142/76766984-d48d1e80-67d3-11ea-9b2c-f28523fbd289.png)

「服務端口」是 v2ray 核心在執行過程中所用的連接埠。如果你親手寫過 V2Ray 的那種複雜的組態，應該對下面的伺服端的片段有印象：

![image](https://user-images.githubusercontent.com/48857142/76767438-95130200-67d4-11ea-9b1d-953719487630.png)

「服務端口」對應的就是「inbounds」中的「port」。

至於「poseidon」區塊中的「localPort」，則是 v2ray-poseidon 這個第三方的後端自身執行時所用的連接埠。我們要做的，是把「連接端口」上的流量轉發到「服務端口」。

因我們採用的是 WebSocket 傳輸協定，故需要將傳入的 http 流量轉換為 WebSocket 流量，這裡涉及到協定轉換。我們假設前端和後端佔用不同的域名。

假設 V2Board 的域名是 abc.com，後端有一個日本節點，節點佔用的域名是 jp.abc.com，因為前後端在同一台機器上，所以你需要在 DNS 解析記錄中將它們指向同一個 IP。然後你需要在「寶塔」面板中新增一個站點，站點的域名叫做「jp.abc.com」，然後在 Nginx 中作出如下設定：

![註解 2020-03-16 223630](https://user-images.githubusercontent.com/48857142/76768871-9c3b0f80-67d6-11ea-9d7c-7ad887e976be.png)

我這裡的「location」後面是「/cctv」，如果你不需要自訂路徑的話，將其改為「/」即可；若要自訂路徑，可在 V2Board 中撰寫：

![2](https://user-images.githubusercontent.com/48857142/76769207-1a97b180-67d7-11ea-9823-ac4293aba1c6.png)

![3](https://user-images.githubusercontent.com/48857142/76769215-1d92a200-67d7-11ea-86ca-a90541f6312d.png)

至此大功告成，然後重新啟動 v2ray.service，就可以使用了。

順帶提一句：由於 3 月 1 日的新網路法規出台，國內直連國外的方式不好使了，你連上後也會很慢，這可不是配置出了問題，而是防火牆又加高了！你需要再購置一台國內的機器作中轉。

**Comment by jinastaka** [comment]
好的 ，我试试 ，不懂的再问你，谢谢你了

**Comment by jinastaka** [comment]
PoorerImmune好心人

**Comment by PoorerImmune** [comment]
> 好的 ，我试试 ，不懂的再问你，谢谢你了

還有最後一點：因為前後端在一台機器上，v2ray.service 自身沒有 SSL 憑證，所以透過 V2Board 的訂閱位址更新出來的節點都有一個問題，就像下面這樣：

![4](https://user-images.githubusercontent.com/48857142/76770867-824efc00-67d9-11ea-81dc-6c8a084a1251.png)

你需要手動改一改。

**Comment by jinastaka** [comment]
谢谢

**Comment by pengzekai** [comment]
> > 好的 ，我试试 ，不懂的再问你，谢谢你了
> 
> 還有最後一點：因為前後端在一台機器上，v2ray.service 自身沒有 SSL 憑證，所以透過 V2Board 的訂閱位址更新出來的節點都有一個問題，就像下面這樣：
> 
> ![4](https://user-images.githubusercontent.com/48857142/76770867-824efc00-67d9-11ea-81dc-6c8a084a1251.png)
> 
> 你需要手動改一改。

你好，我也是将面板和后端放在一台机器上，我按照你的步骤来做了，在后台添加上节点之后也变成蓝色了，但是节点测试还是不能用，测速显示的是‘远程服务器返回错误 503’，不知道是什么情况。可以给个联系方式交流一下吗

**Comment by PoorerImmune** [comment]
> > > 好的 ，我试试 ，不懂的再问你，谢谢你了
> > 
> > 還有最後一點：因為前後端在一台機器上，v2ray.service 自身沒有 SSL 憑證，所以透過 V2Board 的訂閱位址更新出來的節點都有一個問題，就像下面這樣：
> > 
> > ![4](https://user-images.githubusercontent.com/48857142/76770867-824efc00-67d9-11ea-81dc-6c8a084a1251.png)
> > 
> > 你需要手動改一改。
> 
> 你好，我也是将面板和后端放在一台机器上，我按照你的步骤来做了，在后台添加上节点之后也变成蓝色了，但是节点测试还是不能用，测速显示的是‘远程服务器返回错误 503’，不知道是什么情况。可以给个联系方式交流一下吗

這種情況不好說。你先看看伺服器上的時區對應的時鐘和你電腦的誤差是否在 V2Ray 官方強調的範圍內。

狀態指示圓點變藍說明節點的組態沒有問題可以連通。你再排查你的機器和伺服器之間的連線是否正常，不排除 GFW 的干擾。

我只能提供這麼多資訊。
