### ISSUE TITLE
对接sspanel之后，v2ray无法正常上网

### ISSUE THREAD

**Issue by NGXTDN** [ColetteContreras/v2ray-poseidon#38]
docker ws tls debian9.9系统

**Comment by aiastia** [comment]
提问前 请先阅读 这个 
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by ColetteContreras** [comment]
@NGXTDN 请提供你现在使用的情况，配置文件，按哪个文档来的，系统环境，等信息

@aiastia Thanks 这个非常好，都应该好好学习下

**Comment by NGXTDN** [comment]
{
  "poseidon": {
    "panel": "sspanel-webapi",
    "license_key": "",  // 无效，或空的 license key 都会被当成社区版
    "nodeId": 62,		// 面板里添加完节点后生成的自增ID
    // every N seconds
    "checkRate": 60,
    "panelUrl": "https://xxxx", // SSPanel 面板地址
    "panelKey": "xxxx",              // SSPanel 面板的配置文件中的 muKey 的值
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 2,
      "security": "none"
    }
  },
  "log": {
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [
    {
      "port": 10086,
      "protocol": "vmess",
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/"
        }
      },
      "tag": "proxy"
    },
    {
      "listen": "127.0.0.1",
      "port": 10085,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api"
      }
    ],
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  }
}

**Comment by NGXTDN** [comment]
debian9.9系统，用的docker，客户端报错：net/http request canceled(client.timeout exceeded while awaiting headers

**Comment by NGXTDN** [comment]
配置为ws tls 前者ws cdn也试过在同一环境下，能对接皆不可用

**Comment by ColetteContreras** [comment]
文档：[《0202 对接 SSPanel 教程》](https://github.com/ColetteContreras/v2ray-poseidon/wiki/0202-%E5%AF%B9%E6%8E%A5-SSPanel-%E6%95%99%E7%A8%8B)

<img width="800" alt="Snap 2020-02-16 at 1 51 46 PM" src="https://user-images.githubusercontent.com/45476574/74599839-7c270c00-50c3-11ea-91ad-2453a26d75b4.png">

docker 环境下使用命令： `dc logs -f`  来查看日志

**Comment by NGXTDN** [comment]
v2ray-ws    | v2ray -config /etc/v2ray/config.json
v2ray-ws    | V2Ray 4.21.2 (V2Fly, a community-driven edition of V2Ray.) Custom
v2ray-ws    | A unified platform for anti-censorship.
v2ray-ws    | 2020/02/16 13:52:21 [Warning] V2ray-Poseidon: Connected gRPC server "127.0.0.1:10085" 
v2ray-ws    | 2020/02/16 13:52:21 [Debug] V2ray-Poseidon: version: Community-v1.2.2 is going to run
v2ray-ws    | 2020/02/16 13:52:21 [Debug] v2ray.com/core/app/log: Logger started
v2ray-ws    | 2020/02/16 13:52:21 [Warning] v2ray.com/core: V2Ray 4.21.2 started
v2ray-ws    | 2020/02/16 13:52:22 [Debug] [2501122348] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:37618
v2ray-ws    | 2020/02/16 13:52:22 [Info] [2501122348] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
v2ray-ws    | 2020/02/16 13:54:07 [Info] v2ray.com/core/transport/internet/websocket: failed to convert to WebSocket connection > websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

**Comment by aiastia** [comment]
不如 提供 ssh 算了

**Comment by NGXTDN** [comment]
> 不如提供ssh算了

我需要的是解决方法，而不是解决眼前的问题

**Comment by ColetteContreras** [comment]
@NGXTDN 你的 WebServer 是 Nginx 还是 Caddy ，贴上相应的配置，这种一般都是 web server配置的问题

**Comment by ColetteContreras** [comment]
@NGXTDN 教你个测试方法，自己在小火箭上，直接拼 v2ray 节点的信息，不通过 Web server ，先把纯 ws 测试过去。然后再来测试 ws + tls 的。一步一步来

**Comment by NGXTDN** [comment]
我已经测试过TCP可行，ws tls和ws cdn还是无网络，昨天TG里回答的是需要配置caddy证书？

**Comment by ColetteContreras** [comment]
用的什么面板，这些信息都提供一下啊

**Comment by ColetteContreras** [comment]
证书我都帮你搞定了，你只需要搞文档的操作就行，　docker-compose.yml 的内容发过来，还有你面板填写的节点地址。

**Comment by NGXTDN** [comment]
Your sites will be served over HTTPS automatically using Let's Encrypt.
v2ray-ws-tls    | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
v2ray-ws-tls    |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
v2ray-ws-tls    | Please enter your email address to signify agreement and to be notified
v2ray-ws-tls    | in case of issues. You can leave it blank, but we don't recommend it.
v2ray-ws-tls    |   Email address: 2020/02/17 22:53:16 [INFO][bbtec.top] Obtain certificate
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO][.bbtec.top] Obtain: Waiting on rate limiter...
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO][.bbtec.top] Obtain: Done waiting
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO] [bbtec.top] acme: Obtaining bundled SAN certificate
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO] [bbtec.top] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2866358460
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO] [bbtec.top] acme: Could not find solver for: tls-alpn-01
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO] [.bbtec.top] acme: Could not find solver for: http-01
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO] [.bbtec.top] acme: use dns-01 solver
v2ray-ws-tls    | 2020/02/17 22:53:16 [INFO] [.bbtec.top] acme: Preparing to solve DNS-01
v2ray-ws-tls    | 2020/02/17 22:53:17 [INFO] cloudflare: new record for us2.bbtec.top, ID 7e646d82af0868398096e20bc68636ee
v2ray-ws-tls    | 2020/02/17 22:53:17 [INFO] [bbtec.top] acme: Trying to solve DNS-01
v2ray-ws-tls    | 2020/02/17 22:53:17 [INFO] [bbtec.top] acme: Checking DNS record propagation using [127.0.0.11:53]
v2ray-ws-tls    | 2020/02/17 22:53:17 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
v2ray-ws-tls    | 2020/02/17 22:53:17 [INFO] [bbtec.top] acme: Waiting for DNS record propagation.

**Comment by NGXTDN** [comment]
前端用的sspanel

**Comment by NGXTDN** [comment]
2020/02/17 22:53:19 [INFO] [.bbtec.top] acme: Waiting for DNS record propagation.
v2ray-ws-tls    | 2020/02/17 22:53:27 [INFO] [.bbtec.top] The server validated our request
v2ray-ws-tls    | 2020/02/17 22:53:27 [INFO] [.bbtec.top] acme: Cleaning DNS-01 challenge
v2ray-ws-tls    | 2020/02/17 22:53:27 [INFO] [.bbtec.top] acme: Validations succeeded; requesting certificates
v2ray-ws-tls    | 2020/02/17 22:53:27 [INFO] [.bbtec.top] Server responded with a certificate.
v2ray-ws-tls    | done.

**Comment by ColetteContreras** [comment]
提供 `docker-compose.yml` 和 面板里的 `节点地址`，隐私信息使用通用信息替代，比如你的域名用 my.domain 替代，其它隐私信息类似。
