### ISSUE TITLE
V2bord+Caddy+V2ray-poseidon+WS+TLS

### ISSUE THREAD

**Issue by hanjianlin** [ColetteContreras/v2ray-poseidon#39]
苹果小火箭通过订阅 配置 可以正常 使用但是V2rayN 无法使用 
如果通过Caddy 反代 caddy 会报错 （TLS）证书已经整好 域名可以正常连接

Feb 16 14:18:10 v142895 caddy: http: TLS handshake error from *.*.*.*:18335: EOF
Feb 16 14:18:10 v142895 caddy: http: TLS handshake error from *.*.*.*:18334: EOF
Feb 16 14:18:10 v142895 caddy: http: TLS handshake error from *.*.*.*:18336: EOF
Feb 16 14:18:10 v142895 caddy: http: TLS handshake error from *.*.*.*:18340: EOF
 
如果直接通过 直连方式 连接 V2ray-poseidon 端口 Dbug 无数据流 。

**Comment by hanjianlin** [comment]
`{
  "log": {
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [
    {
    "listen": "127.0.0.1",
    "port": 10087,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
    },
    {
      "tag": "proxy",
      "port": 10086,
      "protocol": "vmess",
      "settings": {
        "clients": [],
        "disableInsecureEncryption": false,
        "default": {
          "level": 0,
          "alterId": 16
        }
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/game"
        }
      }
    }
  ],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],    
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
    "poseidon": {
    "panel": "v2board",
    "nodeId": 1,
    "license_key": "",
    "checkRate": 60,
    "webapi": "https://*******",
    "token": "**********",
    "localPort": 10084,
    "useLocalConfig": true
  }
}`
V2ray 服务端 的 config

**Comment by hanjianlin** [comment]
https://**** http://***** {
  root /srv/www
  tls ****@****.com
  gzip
  timeouts none
  proxy /game 127.0.0.1:10086 {
    websocket
    header_upstream -Origin
  }
}
----------------------------------
caddy config

**Comment by ColetteContreras** [comment]
我没用过 V2rayN ，刚才去看了一下是个 Windows 的客户端，鉴于小火箭可以正常使用，猜测可能跟 windows 有关，V2rayN 没啥太大的关系，问题应该是在 tls 证书上，Caddy 上的证书版本都比较新，你可以试下把证书的版本调到 tls1.2 tls1.1 再测试下。

**Comment by hanjianlin** [comment]
解决了~ 修改了 TLS 证书版本果真可以了
-----------------------
    tls {
        protocols tls1.0 tls1.2
    }
--------------------------
Caddy TLS config

**Comment by alfredtofu** [comment]
> ## 解决了~ 修改了 TLS 证书版本果真可以了
> ```
> tls {
>     protocols tls1.0 tls1.2
> }
> ```
> 
> Caddy TLS config

@hanjianlin 请问这个在哪修改的？
