### ISSUE TITLE
websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by hanjianlin** [ColetteContreras/v2ray-poseidon#40]
还是我~ 服务端 和 客户端 配置信息请参照
https://github.com/ColetteContreras/v2ray-poseidon/issues/39

我的问题是 
websocket: close 1006 (abnormal closure): unexpected EOF
---------------------------------------------
2020/02/16 18:22:22 [Info] [3180804144] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: failed to transfer request > websocket: close 1006 (abnormal closure): unexpected EOF
2020/02/16 18:22:22 [Info] [3180804144] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
------------------------------------------------
caddy 则提示
------------------------------------
Feb 16 18:22:22 v142895 caddy: [ERROR] failed to copy buffer:  readfrom tcp 127.0.0.1:23804->127.0.0.1:10086: read tcp *.*.*.*:443->110.82.111.128:19073: read: connection reset by peer
Feb 16 18:22:22 v142895 caddy: [ERROR] failed to copy buffer:  read tcp 127.0.0.1:23804->127.0.0.1:10086: use of closed network connection
-------------------------------------

**Comment by ColetteContreras** [comment]
这个没啥问题，可以正常使用的
