### ISSUE TITLE
出现错误信息

### ISSUE THREAD

**Issue by victoryLV** [ColetteContreras/v2ray-poseidon#42]
使用到宝塔搭建d的sspanel，后台日志如下
![image](https://user-images.githubusercontent.com/32597550/74705501-149dc780-524f-11ea-9cb9-d9aefc088a50.png)

**Comment by ColetteContreras** [comment]
提供所有的配置文件和 SSPanel 上配置的节点地址

**Comment by victoryLV** [comment]
SSPane l 上配置的节点地址us1.ivpn.tech;443;2;tls;ws;path=/|host=us1.ivpn.tech

![image](https://user-images.githubusercontent.com/32597550/74802783-d28b8900-5315-11ea-9ec5-2f2b5e84c345.png)

![image](https://user-images.githubusercontent.com/32597550/74802762-c7385d80-5315-11ea-8df8-e3dbfacb0955.png)
![image](https://user-images.githubusercontent.com/32597550/74802797-da4b2d80-5315-11ea-9399-1377d89315a1.png)

**Comment by ColetteContreras** [comment]
你的 CF 的　API KEY 长度好像不对，再确认下。
![IMAGE 2020-02-19 17:11:31](https://user-images.githubusercontent.com/45476574/74819128-e09fd080-533a-11ea-938e-6c967ec0418b.jpg)

**Comment by ColetteContreras** [comment]
我刚才按你给的信息拼了一个获取用户的 API 地址，发现无法获取到用户的数据。。

```
$ curl --dump-header /dev/stdout 'https://www.ivpn.tech/mod_mu/users?key=Nimssyd&node_id=26'

HTTP/1.1 302 Found
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Wed, 19 Feb 2020 09:17:29 GMT
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Last-Modified: Wed, 19 Feb 2020 09:17:29 GMT
Location: https://sedo.com/search/details/?partnerid=324561&language=us&domain=ivpn.tech&origin=sales_lander_1&utm_medium=Parking&utm_campaign=offerpage
Pragma: no-cache
Server: NginX
X-Adblock-Key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANnylWw2vLY4hUn9w06zQKbhKBfvjFUCsdFlb6TdQhxb9RXWXuI4t31c+o8fYOv/s8q1LGPga3DE1L/tHU4LENMCAwEAAQ==_Kfb6jA+HhCuAYNRUE61bhB6CRkBwuKDurQe+1Bgip/RW/ht1R3ndf7/CEf+6yAMTf6T283e76oTbmmtbffVsLw==
X-Cache-Miss-From: parking-77bd7c94db-gk7pr
```

**Comment by ColetteContreras** [comment]
等调试好了，把敏感信息都重新生成一个，你现在这些信息都暴露了
1. CF 的 API Key 重新生成
2. 重新设置一个 SSPanel 多用户的 key

**Comment by victoryLV** [comment]
> 等调试好了，把敏感信息都重新生成一个，你现在这些信息都暴露了
> 
> 1. CF的API密钥重新生成
> 2. 重新设置一个SSPanel多用户的密钥

大佬，敏感信息我专门修改了，我用的rfchost家的机器出现这个原因的。

**Comment by ColetteContreras** [comment]
已解决，时间没校正的问题 

https://github.com/ColetteContreras/v2ray-poseidon/wiki/05-%E9%87%8D%E8%A6%81%EF%BC%9AV2ray%E8%8A%82%E7%82%B9%E6%97%B6%E9%97%B4%E5%BF%85%E9%A1%BB%E9%85%8D%E7%BD%AE%E6%AD%A3%E7%A1%AE%EF%BC%8C%E5%90%A6%E5%88%99%E5%B0%86%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%EF%BC%8C%E6%8A%A5%E9%94%99-invalid-user
