### ISSUE TITLE
机器无法使用docker且IP被墙

### ISSUE THREAD

**Issue by puzzleindex** [ColetteContreras/v2ray-poseidon#44]
请教一下作者大大能有解决方案吗？

**Comment by ColetteContreras** [comment]
使用的面板是？用 WS 再配上 CDN 即可

**Comment by puzzleindex** [comment]
sspanel  能否给个v2ray的配置文件  不太懂这个  折腾了一整天

**Comment by ColetteContreras** [comment]
请参考这个配置文件 [SSPanel WebSocket](https://github.com/ColetteContreras/v2ray-poseidon/blob/master/docker/sspanel/ws/config.json)
只需要填上面板的信息然后把 10086 改成 80，就可以对接 CDN 了。

**Comment by puzzleindex** [comment]
好的 非常感谢

**Comment by puzzleindex** [comment]
按照您给的那个配置文件修改10086端口为80后  不成功  v2ray log看上去没有报错  但是直接访问域名无法访问

**Comment by ColetteContreras** [comment]
直接访问域名肯定是没法访问的，又没加网站内容。。
