### ISSUE TITLE
目前是否无法使用v2board的中转功能？

### ISSUE THREAD

**Issue by starP-W** [ColetteContreras/v2ray-poseidon#46]
尝试使用v2board进行中转操作，设置如下
![image](https://user-images.githubusercontent.com/22597802/74825732-6163ca00-5345-11ea-82a5-eb7ffb99d035.png)
其中2与3在同一台机器上，尝试通过2进行中转至节点1。但是实际连接时发现节点2与3依旧显示相同的IP，进入容器查看时也没有发现两台机器进行过连接。不知道是设置有误还是暂时未支持v2board的中转？

**Comment by chen-ran** [comment]
能否中转与面板没有关系，父节点功能并非中转功能。

**Comment by ColetteContreras** [comment]
我也没用过这个的中转，你研究研究告诉我下吧，哈哈～

**Comment by starP-W** [comment]
> 能否中转与面板没有关系，父节点功能并非中转功能。

好吧，感谢解答，我再看看这个面板
