### ISSUE TITLE
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled

### ISSUE THREAD

**Issue by peter168111** [ColetteContreras/v2ray-poseidon#48]
后台好多这个报错（影响速度，会断流）：v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
发现错误代码在：v2ray-core-master\app\proxyman\outbound\handler.go 这个文件里的报错：
// Dispatch implements proxy.Outbound.Dispatch.
func (h *Handler) Dispatch(ctx context.Context, link *transport.Link) {
	if h.mux != nil && (h.mux.Enabled || session.MuxPreferedFromContext(ctx)) {
		if err := h.mux.Dispatch(ctx, link); err != nil {
			newError("failed to process mux outbound traffic").Base(err).WriteToLog(session.ExportIDToError(ctx))
			common.Interrupt(link.Writer)
		}
	} else {
		if err := h.proxy.Process(ctx, link, h); err != nil {
			// Ensure outbound ray is properly closed.
			newError("failed to process outbound traffic").Base(err).WriteToLog(session.ExportIDToError(ctx))
			common.Interrupt(link.Writer)
		} else {
			common.Must(common.Close(link.Writer))
		}
		common.Interrupt(link.Reader)
	}
}

**Comment by ColetteContreras** [comment]
配置文件，在什么样的使用场景下？还有就是先测试一下使用 v2ray-core 原版的是否有问题，如果也有问题，则向 v2ray-core 提 issue

**Comment by peter168111** [comment]
tcp和ws+tls模式都出这个报错。安装完只改了config.json和制作了.key和.crt文件。
config.json文件只有下面配置段：
{
  "poseidon": {
    "panel": "v2board",         // 这一行必须存在，且不能更改
    "nodeId": 1,                // 你的节点 ID 和 v2board 里的一致
    "license_key": "PUT YOU LICENSE KEY HERE",      // 你获得的 v2ray-poseidon 的授权码写到这里，期待后面直接在 v2board 里配置该项内容
    "checkRate": 60,            // 每隔多长时间同步一次配置文件、用户、上报服务器信息
    "webapi": " https://我的域名",// v2board 的域名信息
    "token": "25wrwrerwerwe131",   // v2board 和 v2ray-poseidon 的通信密钥,这个没错。
    "localPort": 10084 // 本地 api, dokodemo-door,　监听在哪个端口，不能和服务端口相同
  }
}

**Comment by peter168111** [comment]
使用安卓手机和WINDOWS客户端代理后，打开链接都报这个错误。

**Comment by ColetteContreras** [comment]
> tcp和ws+tls模式都出这个报错。安装完只改了config.json和制作了.key和.crt文件。使用233一键脚本安装的v2ray没这个问题。

如果是这样的话，估计得等我更新 v2ray-core 之后再测试下了。

> 使用安卓手机和WINDOWS客户端代理后，打开链接都报这个错误。

iOS 客户端没事儿么？

**Comment by thank243** [comment]
mux建议关闭。

**Comment by wfy8002** [comment]
请教一下：
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2rya.com/core/proxy/vmess/outbound:connection ends >v2ray.com/core/proxy/vmess/outbound:failed to read header >v2ray.com/core/proxy/vmess/encoding:filed to read response header >EOF
服务器配置：
 "log": {
    "loglevel": "none"
  },
  // List of inbound proxy configurations.
         "inbounds": [
                {
                        "port": 38555,
                        "protocol": "vmess",
                        "settings": {
                                "clients": [
                                        {
                                                "id": "*****",
                                                "level": 1,
                                                "alterId": 0
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "tcp"
                        },
                        "sniffing": {
                                "enabled": true,
===================================
客户端配置：
 "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8",
      {
        "address": "8.8.8.8",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ],
        "port": 53
      }
    ]
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [],
        "enabled": false
      },
      "tag": "socks"
    },
    {
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "####",
            "port": 39555,
            "users": [
              {
                "alterId": 0,
                "encryption": "",
                "flow": "",
                "id": "####",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
