### ISSUE TITLE
sspanel对接纯ws显示成功 没有网络

### ISSUE THREAD

**Issue by ccgakki** [ColetteContreras/v2ray-poseidon#49]
cd ws下只修改config的panelurl和key，nodeid，面板前端这样填：域名;10086;2;ws;;path=/|host=域名，
docker log：2020/02/22 21:08:09 [Debug] [2087959782] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:58716
2020/02/22 21:08:09 [Info] [2087959782] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2020/02/22 21:08:22 [Error] V2ray-Poseidon: panel#do > get node info > get node info from api err > Get https://sspanel域名/mod_mu/nodes/3/info?key=NimaQu&node_id=3: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
然后是docker container ls 情况：
permitted by applicable law.
root@vm212466:~# docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                    NAMES
7650800054d3        v2cc/poseidon       "/usr/bin/entrypoint…"   About an hour ago   Up About an hour    80/tcp, 443/tcp, 0.0.0.0:80->10086/tcp   v2ray-ws
可以点亮后端，就是ping超时，shadowrocket连接不上显示超时。希望作者有空解答一下，谢谢🙏🏻

**Comment by ColetteContreras** [comment]
节点地址得填 `域名;80;2;ws;;path=/|host=域名`，不是 10086

**Comment by ColetteContreras** [comment]
还有貌似是你网络问题，连接 webapi 会有问题，可以先把主机的 dns 解析服务器设置成 1.1.1.1 和 8.8.8.8，然后重启下 docker

**Comment by ccgakki** [comment]
是的。修改一下dns。和后端参数OK了。感谢大大
