### ISSUE TITLE
双协议栈VPS无法正常对接SSPANEL

### ISSUE THREAD

**Issue by Lightmani** [ColetteContreras/v2ray-poseidon#53]
面板节点地址配置为：域名;443;2;tls;ws;path=/|host=域名
在这种情况下，面板自动将节点IP解析为域名对应的IPV4地址

但是当我在节点vps启动v2时，会遇到报错，提示当前IP与面板IP不匹配。
查看日志发现，节点V2获取到的本机IP为IPV6地址，而面板自动解析的地址为IPV4地址，两者不同故而无法对接。
当我禁用节点的IPV6协议后，可以正常对接使用。

我在想能否让v2获取本机IP时默认使用IPV4协议，以便在节点同时支持IPV4&V6的情况下正常对接。

**Comment by ColetteContreras** [comment]
https://github.com/ColetteContreras/v2ray-poseidon/wiki/0202-%E5%AF%B9%E6%8E%A5-SSPanel-%E6%95%99%E7%A8%8B

![image](https://user-images.githubusercontent.com/45476574/76421627-ea1ed480-63de-11ea-8379-483822d3f5a6.png)

这一步做了吗？

**Comment by ColetteContreras** [comment]
这个其实和后端无关，你在节点用 curl 请求一下你的面板，就会发现，你面板获取到的是 IPv6 的地址，除非你把 IPv6 禁止了，解决办法就是：面板不校验节点IP，或禁节点的 IPv6

**Comment by Lightmani** [comment]
我的面板套CF了而且没有IPV6地址，我看了下响应日志，获取到的都是CF的V4的回源IP。

我想还是禁用节点的IPV6吧，这么做影响也不是很大。

谢谢开发者的建议。
