### ISSUE TITLE
请求更新一下 geosite.dat 文件

### ISSUE THREAD

**Issue by Liaozhebin** [ColetteContreras/v2ray-poseidon#55]
自定义V2ray配置文件，显示找不到 `"geosite:category-ads-all"`
自我排查，作者打包的 `geosite` 文件太旧了，没有这个库内容，自行在 `v2ray github` 下载 `dat` 文件后，重启即可正常使用。

**Comment by yywudi** [comment]
建议同步更新为这个项目的文件 https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by ColetteContreras** [comment]
测试版在这，可以测试，需要手动下载安装（因为还不是正式版，脚本不会安装测试版本的

https://github.com/ColetteContreras/v2ray-poseidon/releases/tag/v1.4.8

使用了 @yywudi 大佬提供的源，并在每次启动前检查一下文件的修改时间，如果超过1周了，则尝试更新操作。
