### ISSUE TITLE
对接v2board 安装完成后提示443端口拒绝访问，两台vps同样的错误，端口确认已经打开

### ISSUE THREAD

**Issue by wbmvincent** [ColetteContreras/v2ray-poseidon#57]
[root@v2ray-a ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
V2Ray-Poseidon v1.4.7 (core: 4.21.2)
2020/03/31 16:32:48 [Warning] V2ray-Poseidon: panel: V2board
2020/03/31 16:32:48 [Warning] V2ray-Poseidon: node > check interval 60s
2020/03/31 16:32:48 [Warning] V2ray-Poseidon: node > speed limit unlimited
2020/03/31 16:32:48 [Warning] V2ray-Poseidon: user > max online ip count 0
2020/03/31 16:32:48 [Warning] V2ray-Poseidon: user > speed limit unlimited
2020/03/31 16:32:48 [Error] V2ray-Poseidon: fetch v2ray config error: http get > Get "https://hk.smallv.top/api/v1/server/poseidon/config?local_port=10084&node_id=8&token=smallv-v2ray-sg-b": dial tcp 35.198.235.186:443: connect: connection refused

**Comment by Liaozhebin** [comment]
密钥太短了，去搜索token 生成器。生成通讯密钥

**Comment by wbmvincent** [comment]
端口不能访问跟

> 密钥太短了，去搜索token 生成器。生成通讯密钥

端口拒绝访问跟token有什么关系？问题是我有一台vps同样设置正常连接啊，另外两台都是这个同样的问题…

**Comment by Liaozhebin** [comment]
既然已经有部署成功的一台了，不如销毁两台不行的，重建重部署。🙂

wbmvincent <notifications@github.com> 于 2020年4月1日周三 上午2:10写道：

**Comment by wbmvincent** [comment]
两台新的都重新安装系统重新部署了好几次，防火墙全关了之后还是不行，一直提示这个错误

**Comment by cyril-cheng** [comment]
端口冲突也会有这个提示

**Comment by ColetteContreras** [comment]
> [root@v2ray-a ~]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
> V2Ray-Poseidon v1.4.7 (core: 4.21.2)
> 2020/03/31 16:32:48 [Warning] V2ray-Poseidon: panel: V2board
> 2020/03/31 16:32:48 [Warning] V2ray-Poseidon: node > check interval 60s
> 2020/03/31 16:32:48 [Warning] V2ray-Poseidon: node > speed limit unlimited
> 2020/03/31 16:32:48 [Warning] V2ray-Poseidon: user > max online ip count 0
> 2020/03/31 16:32:48 [Warning] V2ray-Poseidon: user > speed limit unlimited
> 2020/03/31 16:32:48 [Error] V2ray-Poseidon: fetch v2ray config error: http get > Get "https://hk.smallv.top/api/v1/server/poseidon/config?local_port=10084&node_id=8&token=smallv-v2ray-sg-b": dial tcp 35.198.235.186:443: connect: connection refused

你可以在节点机器上运行下面的命令，看是否能正常访问，如果不能访问就是网络或面板机的配置问题，该问题和后端节点无关。
```
curl 'https://hk.smallv.top/api/v1/server/poseidon/config?local_port=10084&node_id=8&token=smallv-v2ray-sg-b'
```
