### ISSUE TITLE
填写授权码以后无网络

### ISSUE THREAD

**Issue by 2100056561** [ColetteContreras/v2ray-poseidon#58]
为什么我在config.json里面填写了license key并重启了v2ray服务器以后 无网络连接

而删除license key以后就恢复了网络连接

**Comment by ColetteContreras** [comment]
购买授权时的域名和填在 `config.json` 里面 `WebAPI` 的域名需要完全一致。 注意：`www.abc.com `和 `abc.com` 不是相同的域名。

**Comment by 2100056561** [comment]
购买授权时的域名和填在 config.json 里面 WebAPI 的域名是一致的，重启v2ray以后还是无法访问到网络
