### ISSUE TITLE
使用中转后无办法限制ip数

### ISSUE THREAD

**Issue by kakakakarr** [ColetteContreras/v2ray-poseidon#60]
我用的是v2board，只有添加了中转，在json中即便设置了用户同时在线 IP 数限制，也没办法正确生效，怀疑后端没办法正确获取转发后的源IP导致的

**Comment by ColetteContreras** [comment]
中转需要正确地将用户IP转发到后端，可以把后端的配置和中转的配置发过来

**Comment by kakakakarr** [comment]
后端的配置如下：

```
{
  "poseidon": {
    "panel": "v2board",         // 这一行必须存在，且不能更改
    "nodeId": 10,                // 你的节点 ID 和 v2board 里的一致
    "checkRate": 60,            // 每隔多长时间同步一次配置文件、用户、上报服务器信息
    "webapi": "https://****xyz",// v2board 的域名信息
    "token": "3R*******4",   // v2board 和 v2ray-poseidon 的通信密钥

    "speedLimit": 0, // 节点限速 单位 字节/s 0 表示不限速
    "user": {
      "maxOnlineIPCount": 3,  // 用户同时在线 IP 数限制 0 表示不限制
      "speedLimit": 0         // 用户限速 单位 字节/s 0 表示不限速
    },

    "localPort": 10084 // 本地 api, dokodemo-door,　监听在哪个端口，不能和服务端口相同
  }
}
```

中转使用iptables以及vnet还有gosh

下面是iptables，不能回源，在日志下看到是中转Ip,隧道的看到是127.0.0.1的内网
```
iptables -t nat -A POSTROUTING -j MASQUERADE
iptables -t nat -A PREROUTING -d 服务器A的IP -p tcp --dport A端口 -j DNAT --to 服务器B的IP:B端
```

**Comment by kakakakarr** [comment]
> v2ray 是 tcp 的还是 ws-tls

隧道的话tcp跟ws-tls都试过，一样的情况
iptables只试过ws-tls

**Comment by ColetteContreras** [comment]
测试过的方法：使用 HAProxy 做中转 TCP，参数上加上 `send-proxy` 选项。

1. HAProxy配置的方式 （HAProxy 会将请求的真实IP加到数据包中）

```
frontend test_frontend
  bind 0.0.0.0:10086
  mode tcp
  default_backend test_backend
backend test_backend
  mode tcp
  server test your-backend-server:10086 send-proxy
```

2. 后端需要开启该功能（解包 HAProxy 封装的用户 IP）

- 修改 /etc/systemd/system/v2ray.service 在 [Service] 下加一行内容
`Environment="ENABLE_PROXY_PROTOCOL=1" `，然后重启 v2ray 服务

**Comment by Lightmani** [comment]
> 测试过的方法：使用 HAProxy 做中转 TCP，参数上加上 `send-proxy` 选项。
> 
> 1. HAProxy配置的方式 （HAProxy 会将请求的真实IP加到数据包中）
> 
> ```
> frontend test_frontend
>   bind 0.0.0.0:10086
>   mode tcp
>   default_backend test_backend
> backend test_backend
>   mode tcp
>   server test your-backend-server:10086 send-proxy
> ```
> 
> 1. 后端需要开启该功能（解包 HAProxy 封装的用户 IP）
> 
> * 修改 /etc/systemd/system/v2ray.service 在 [Service] 下加一行内容
>   `Environment="ENABLE_PROXY_PROTOCOL=1" `，然后重启 v2ray 服务

请问作者，目前有iptables的解决方法吗？我用的sspanel通过iptables方式中转，也遇到了这个情况。
配置是ws+tls，V2配置文件用的是您的项目wiki里的ws+tls的模板文件

**Comment by ColetteContreras** [comment]
> > 测试过的方法：使用 HAProxy 做中转 TCP，参数上加上 `send-proxy` 选项。
> > 
> > 1. HAProxy配置的方式 （HAProxy 会将请求的真实IP加到数据包中）
> > 
> > ```
> > frontend test_frontend
> >   bind 0.0.0.0:10086
> >   mode tcp
> >   default_backend test_backend
> > backend test_backend
> >   mode tcp
> >   server test your-backend-server:10086 send-proxy
> > ```
> > 
> > 
> > 
> > 1. 后端需要开启该功能（解包 HAProxy 封装的用户 IP）
> > 
> > 
> > * 修改 /etc/systemd/system/v2ray.service 在 [Service] 下加一行内容
> >   `Environment="ENABLE_PROXY_PROTOCOL=1" `，然后重启 v2ray 服务
> 
> 请问作者，目前有iptables的解决方法吗？我用的sspanel通过iptables方式中转，也遇到了这个情况。
> 配置是ws+tls，V2配置文件用的是您的项目wiki里的ws+tls的模板文件

在我的印象中 iptables 是做不到的，因为你不可能直接修改 SRC 的 IP 地址为用户真实的 IP 地址，然后把数据包转发给你的节点。

可以这样，中转用 Nginx ，节点那边就直接用 WS，证书配置在 Nginx 这里，然后再把客户端 IP 添加到 Header 头部转发给节点。

```
proxy_set_header  X-Real-IP $remote_addr;
proxy_set_header  X-Forwarded-For $remote_addr;
```

**Comment by Lightmani** [comment]
> > > 测试过的方法：使用 HAProxy 做中转 TCP，参数上加上 `send-proxy` 选项。
> > > 
> > > 1. HAProxy配置的方式 （HAProxy 会将请求的真实IP加到数据包中）
> > > 
> > > ```
> > > frontend test_frontend
> > >   bind 0.0.0.0:10086
> > >   mode tcp
> > >   default_backend test_backend
> > > backend test_backend
> > >   mode tcp
> > >   server test your-backend-server:10086 send-proxy
> > > ```
> > > 
> > > 
> > > 
> > > 1. 后端需要开启该功能（解包 HAProxy 封装的用户 IP）
> > > 
> > > 
> > > * 修改 /etc/systemd/system/v2ray.service 在 [Service] 下加一行内容
> > >   `Environment="ENABLE_PROXY_PROTOCOL=1" `，然后重启 v2ray 服务
> > 
> > 
> > 请问作者，目前有iptables的解决方法吗？我用的sspanel通过iptables方式中转，也遇到了这个情况。
> > 配置是ws+tls，V2配置文件用的是您的项目wiki里的ws+tls的模板文件
> 
> 在我的印象中 iptables 是做不到的，因为你不可能直接修改 SRC 的 IP 地址为用户真实的 IP 地址，然后把数据包转发给你的节点。
> 
> 可以这样，中转用 Nginx ，节点那边就直接用 WS，证书配置在 Nginx 这里，然后再把客户端 IP 添加到 Header 头部转发给节点。
> 
> ```
> proxy_set_header  X-Real-IP $remote_addr;
> proxy_set_header  X-Forwarded-For $remote_addr;
> ```

谢谢大佬
我下次试一试

**Comment by kakakakarr** [comment]
> > > 测试过的方法：使用 HAProxy 做中转 TCP，参数上加上 `send-proxy` 选项。
> > > 
> > > 1. HAProxy配置的方式 （HAProxy 会将请求的真实IP加到数据包中）
> > > 
> > > ```
> > > frontend test_frontend
> > >   bind 0.0.0.0:10086
> > >   mode tcp
> > >   default_backend test_backend
> > > backend test_backend
> > >   mode tcp
> > >   server test your-backend-server:10086 send-proxy
> > > ```
> > > 
> > > 
> > > 
> > > 1. 后端需要开启该功能（解包 HAProxy 封装的用户 IP）
> > > 
> > > 
> > > * 修改 /etc/systemd/system/v2ray.service 在 [Service] 下加一行内容
> > >   `Environment="ENABLE_PROXY_PROTOCOL=1" `，然后重启 v2ray 服务
> > 
> > 
> > 请问作者，目前有iptables的解决方法吗？我用的sspanel通过iptables方式中转，也遇到了这个情况。
> > 配置是ws+tls，V2配置文件用的是您的项目wiki里的ws+tls的模板文件
> 
> 在我的印象中 iptables 是做不到的，因为你不可能直接修改 SRC 的 IP 地址为用户真实的 IP 地址，然后把数据包转发给你的节点。
> 
> 可以这样，中转用 Nginx ，节点那边就直接用 WS，证书配置在 Nginx 这里，然后再把客户端 IP 添加到 Header 头部转发给节点。
> 
> ```
> proxy_set_header  X-Real-IP $remote_addr;
> proxy_set_header  X-Forwarded-For $remote_addr;
> ```

谢谢大佬，我尝试了下Nginx中转，但是在Nginx配置证书后就无法连接了，不带证书就可以。不知道tls具体正确要怎么操作呢？

**Comment by ColetteContreras** [comment]
> > > > 测试过的方法：使用 HAProxy 做中转 TCP，参数上加上 `send-proxy` 选项。
> > > > 
> > > > 1. HAProxy配置的方式 （HAProxy 会将请求的真实IP加到数据包中）
> > > > 
> > > > ```
> > > > frontend test_frontend
> > > >   bind 0.0.0.0:10086
> > > >   mode tcp
> > > >   default_backend test_backend
> > > > backend test_backend
> > > >   mode tcp
> > > >   server test your-backend-server:10086 send-proxy
> > > > ```
> > > > 
> > > > 
> > > > 
> > > > 1. 后端需要开启该功能（解包 HAProxy 封装的用户 IP）
> > > > 
> > > > 
> > > > * 修改 /etc/systemd/system/v2ray.service 在 [Service] 下加一行内容
> > > >   `Environment="ENABLE_PROXY_PROTOCOL=1" `，然后重启 v2ray 服务
> > > 
> > > 
> > > 请问作者，目前有iptables的解决方法吗？我用的sspanel通过iptables方式中转，也遇到了这个情况。
> > > 配置是ws+tls，V2配置文件用的是您的项目wiki里的ws+tls的模板文件
> > 
> > 
> > 在我的印象中 iptables 是做不到的，因为你不可能直接修改 SRC 的 IP 地址为用户真实的 IP 地址，然后把数据包转发给你的节点。
> > 可以这样，中转用 Nginx ，节点那边就直接用 WS，证书配置在 Nginx 这里，然后再把客户端 IP 添加到 Header 头部转发给节点。
> > ```
> > proxy_set_header  X-Real-IP $remote_addr;
> > proxy_set_header  X-Forwarded-For $remote_addr;
> > ```
> 
> 谢谢大佬，我尝试了下Nginx中转，但是在Nginx配置证书后就无法连接了，不带证书就可以。不知道tls具体正确要怎么操作呢？

这个可以自己查询 nginx tls 即可，与后端无关了

**Comment by kakakakarr** [comment]
> 测试过的方法：使用 HAProxy 做中转 TCP，参数上加上 `send-proxy` 选项。
> 
> 1. HAProxy配置的方式 （HAProxy 会将请求的真实IP加到数据包中）
> 
> ```
> frontend test_frontend
>   bind 0.0.0.0:10086
>   mode tcp
>   default_backend test_backend
> backend test_backend
>   mode tcp
>   server test your-backend-server:10086 send-proxy
> ```
> 
> 1. 后端需要开启该功能（解包 HAProxy 封装的用户 IP）
> 
> * 修改 /etc/systemd/system/v2ray.service 在 [Service] 下加一行内容
>   `Environment="ENABLE_PROXY_PROTOCOL=1" `，然后重启 v2ray 服务

如果是在docker上运行，请问下该如何修改呢？

**Comment by waxi-i** [comment]
Nginx 四层转发 可以透传ip吗
