### ISSUE TITLE
Docker下运行poseidon带ip中转后无法连接

### ISSUE THREAD

**Issue by kakakakarr** [ColetteContreras/v2ray-poseidon#61]
用的是ws+tls

看了日志是可以显示源IP地址但是会报tls握手错误的信息。

错误为http: TLS handshake error from 真实源ip:端口: EOF

**Comment by ColetteContreras** [comment]
使用 Nginx 中转方案？还是 HAProxy。

**Comment by kakakakarr** [comment]
> 使用 Nginx 中转方案？还是 HAProxy。

Nginx，我发现只要不加tls就正常，加了tls就会出错，晚点尝试把hosts转发也加上去

**Comment by ColetteContreras** [comment]
你后端的证书和中转的证书是怎样的？
