### ISSUE TITLE
后端多开失败

### ISSUE THREAD

**Issue by zhzhyu** [ColetteContreras/v2ray-poseidon#64]
![image](https://user-images.githubusercontent.com/58381672/80438876-d05a3200-8937-11ea-87b9-760fbdc4379c.png)
只能开一个实例，开启不了第二个

**Comment by ColetteContreras** [comment]
有创建对应实例的配置文件么？仔细按文档再核对下，有问题可以把配置文件贴上来

```
systemctl status 'v2ray@*' 
```
