### ISSUE TITLE
V2Board面板失联后上报流量问题

### ISSUE THREAD

**Issue by xb0or** [ColetteContreras/v2ray-poseidon#65]
面板失联后 会丢失从失联到恢复那一段时间的流量统计
希望面板失联后会持续采集流量然后等到面板恢复的时候一次性提交

**Comment by ColetteContreras** [comment]
确认了代码，如果面板失联，则获取用户会失败，也就不会继续去采集 v2ray 的流量并重置，所以流量统计会一直在，直到从面板获取用户成功，才会采集 v2ray 流量并重置。只有一种情况会丢失，那就是在成功获取了用户后，上报流量时就失败（获取用户成功后 3秒内），解决办法就是提高面板的可靠性。
