### ISSUE TITLE
关于CDN的提问

### ISSUE THREAD

**Issue by LookCosplay** [ColetteContreras/v2ray-poseidon#70]
IP;80;2;ws;;path=/|host=CF CDN

CFCDN开启橙色云朵

我想问下 前面的IP 可以换成CDN 并且开启橙色的云朵吗? 

后面的CDN 可以换成 不是V2ray服务器的ip吗?

**Comment by ColetteContreras** [comment]
可以开启 cdn ，连接时候的 IP 改成域名，最后的 `|host=` 可以删除
