### ISSUE TITLE
请问社区版的有效用户数50人限制

### ISSUE THREAD

**Issue by amColinzzz** [ColetteContreras/v2ray-poseidon#78]
> 首先,感谢作者的优秀作品,如果有一天拿来盈利,一定买授权版.

wiki给出的定义:50人限制的真实含义：面板有效用户数。有效用户为那些有权连接到你的节点的用户，一般来说就是流量没超、还没到期、以及未被管理员封禁的那些用户。
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
我的问题:
4个假定条件:

1. 假定我的面板有100注册用户

2. 假定我只有两个节点A和B

3. 假定我两个节点都用的v2ray-poseidon部署的后端

4. 假定A节点有49人有权限,B节点有49人有权限; 那么这样我的面板有效用户是98人

Q :那么请问这样的话,用户数算不算超出使用范围?我的理解是不算...希望解答,谢谢您.

**Comment by TerrorbladeART** [comment]
纠结这些有什么意义呢？ 免费人数本来就是给测试的 50人不够你测试？ 巴拉巴拉一大堆

**Comment by amColinzzz** [comment]
> 纠结这些有什么意义呢？ 免费人数本来就是给测试的 50人不够你测试？ 巴拉巴拉一大堆

大早上的你是死爹了还是死妈了?还是你爹跟你小姨子跑了?张嘴就喷粪.我来确认问题,你知就言语,不知就闭嘴.

**Comment by TerrorbladeART** [comment]
厉害 素质玩家 我惹不起...

**Comment by amColinzzz** [comment]
> 厉害 素质玩家 我惹不起...

自己出口成脏，还说别人素质？就是君子太多了，才让你这种无脑巨婴洋洋得意。沙雕玩家。

**Comment by TerrorbladeART** [comment]
想白嫖就直说嘛 巴拉巴拉的 还确认一下 又不是不给你嫖 那么激动干啥呢 气坏自己好吗？

**Comment by amColinzzz** [comment]
> 纠结这些有什么意义呢？ 免费人数本来就是给测试的 50人不够你测试？ 巴拉巴拉一大堆
操死你妈哎。人家拿出来社区版就是保持开源精神，并且通过大量的免费用户使用过程中遇到的问题来改善项目，保证付费用户更好使用，要不然CentOS会继承红帽所有的东西给你用？
操死你妈给你说这么多干嘛，
你以为谁都跟你一样，整天白嫖你妈，你妈就喜欢被白嫖，才有了你。沙雕

**Comment by TerrorbladeART** [comment]
别气 别气 想白嫖说声就行 我给你买 没事的 别激动

**Comment by amColinzzz** [comment]
> 别气 别气 想白嫖说声就行 我给你买 没事的 别激动

每次和你娘做爱的时候都气血上涌，难以抑制。怎梦不鸡动呢，不鸡动，怎么让你老娘爽？

**Comment by TerrorbladeART** [comment]
啧啧啧 这素质

**Comment by amColinzzz** [comment]
> 啧啧啧 这素质

别特么说素质素质的了？对一条满嘴喷粪，整天盈盈狂吠的疯狗，还要待之以礼？你也配？求求你当个人吧，别特么整天全世界你最屌，全世界你最正义，全世界都是你家开的，大早上就见人就怼，你不为了你，也为了你爹娘少挨点骂，为了你闺女不被人搞，积点德吧

**Comment by TerrorbladeART** [comment]
翻翻记录 好好看看 你这样和哥loser有什么区别

**Comment by TerrorbladeART** [comment]
抱歉 你就是...

**Comment by amColinzzz** [comment]
> 翻翻记录 好好看看 你这样和个loser有什么区别

我不是说了吗，你的眼里你最屌，你的严厉你最争议，别人都是loser，都是你爹，都是你亲爹，都是操翻你妈的人，
你天天出来怼人，你娘，你姥姥，你家里的妇女们，不天天给人嘴上操，你妈下面都生蛆了。拿着你妈卖逼的钱上个网还出来打嘴炮

**Comment by TerrorbladeART** [comment]
好了好了 看把你气的 有必要吗?大不了我帮你买哥授权呗 对不对 有必要这样嘛.....气坏自己多不好

**Comment by amColinzzz** [comment]
> 好了好了 看把你气的 有必要吗?大不了我帮你买哥授权呗 对不对 有必要这样嘛.....气坏自己多不好

本来以为你只是个无脑巨婴，没想到你还是个吹牛逼的土驴。是不是你出门踩到别人了都把整条马路买来送人？

**Comment by TerrorbladeART** [comment]
啧啧啧 无药可救了你 张口闭口不是脏话就是脏话 真是个loser....这素质也是无敌了你

**Comment by amColinzzz** [comment]
> 啧啧啧 无药可救了你 张口闭口不是脏话就是脏话 真是个loser....这素质也是无敌了你

这是你自找的，土驴！鳖孙玩意，什么东西

**Comment by lawshon** [comment]
能别瞎BB了吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: amColinzzz <notifications@github.com&gt;
发送时间: 2020年5月24日 12:16
收件人: ColetteContreras/v2ray-poseidon <v2ray-poseidon@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ColetteContreras/v2ray-poseidon] 请问社区版的有效用户数50人限制 (#78)





  
好了好了 看把你气的 有必要吗?大不了我帮你买哥授权呗 对不对 有必要这样嘛.....气坏自己多不好
  
本来以为你只是个无脑巨婴，没想到你还是个吹牛逼的土驴。是不是你出门踩到别人了都把整条马路买来送人？

**Comment by TerrorbladeART** [comment]
好了好了 都别Bb了 loser 好好努力吧 加油哦

**Comment by amColinzzz** [comment]
> 好了好了 都别Bb了 loser 好好努力吧 加油哦

卢你妈嘞个血逼的ser,傻逼，加油操死你亲妈

**Comment by ColetteContreras** [comment]
只要对面板玩的熟，可以通过各种办法让一个节点只有 <= 50 个有效用户，比如套餐就卖 50 份，超过了这个套餐就下架，其它用户再购买用新的套餐，不同套餐指向不同的后端节点。

`有效用户`是后端通过面板接口获取的用户数，这是接口的代码，你可以手动构造一个请求调用一下。https://github.com/Anankke/SSPanel-Uim/blob/58c65e95e4cc17c15197d013f5a3cb93cc877379/src/Controllers/Mod_Mu/UserController.php#L27
