### ISSUE TITLE
更新V2ray Core

### ISSUE THREAD

**Issue by OneHappyForever** [ColetteContreras/v2ray-poseidon#79]
最近有新的漏洞，新版本修复。

目前的版本好像在用4.21.1版本，是去年十月出的，已经8个月了。

希望能更新一下。

**Comment by ColetteContreras** [comment]
6.20 号之前完成更新

**Comment by OneHappyForever** [comment]
谢谢大佬！加强了我们对这个软件的信心。

我看因为漏洞最近V2Ray差不多天天有更新，可能等一等几天看看会不会再出新的版本？好像四个小时前又出了4.23.4
