### ISSUE TITLE
建议跟进V2Ray内核的安全更新 release@v4.23.4

### ISSUE THREAD

**Issue by Liaozhebin** [ColetteContreras/v2ray-poseidon#81]
v4.23.4
@xiaokangwang xiaokangwang released this yesterday

Fix
Issued further fixs for VMess weakness described in v2ray#2523 v2ray#2539
Issued a fix for Fake HTTP Header weakness described in v2ray#2537

v4.23.3
@xiaokangwang xiaokangwang released this 3 days ago · 18 commits to master since this release

Fix
Issued an emergency fix for VMess weakness described in v2ray#2523
This fix can significantly hindrance attack based on the weakness described. Only servers need to be updated to apply this emergency fix, it not expected for well-behaved clients to be influenced. A more permanent solution is underway.

**Comment by ColetteContreras** [comment]
已更新
