### ISSUE TITLE
用Haproxy中转ws+tls到v2ray后端时，如何上报用户真实IP给后端。

### ISSUE THREAD

**Issue by Chan110011** [ColetteContreras/v2ray-poseidon#83]
在后端情况为TCP时，在haproxy使用send-proxy可以上报用户真实IP。

但如果后端情况为ws+tls时，经过测试，haproxy使用send-proxy会照成客户端无法连接。

后者的情况该如何解决呢？

**Comment by ColetteContreras** [comment]
服务端和客户端报错日志贴一下

**Comment by Chan110011** [comment]
客户端报错日志：
> 2020/06/07 11:02:39 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://ascv.fgerg.xlddns.xyz:10870/www):  > EOF] > v2ray.com/core/common/retry: all retry attempts failed

服务端报错日志：
> v2ray[24806]: 2020/06/07 11:05:47 http: TLS handshake error from 112.132.153.3:52754: tls: first record does not look like a TLS handshake

**Comment by ColetteContreras** [comment]
> 但如果后端情况为ws+tls时，经过测试，haproxy使用send-proxy会照成客户端无法连接。

这个等我有时间了测试下

**Comment by ColetteContreras** [comment]
最新版已经支持该功能 https://t.me/v2ray_poseidon/73286
