### ISSUE TITLE
对接SSPanel,某天后流量上报开始出错,为0

### ISSUE THREAD

**Issue by iddddg** [ColetteContreras/v2ray-poseidon#85]
代理正常配置如下
```json
{
    "poseidon": {
        "panel": "sspanel-webapi",
        "license_key": "",
        "nodeId": 1,
        "checkRate": 60,
        "panelUrl": "xxxxxx",
        "panelKey": "xxxxxx",
        "user": {
            "inboundTag": "proxy",
            "level": 0,
            "alterId": 2,
            "security": "none"
        }
    },
    "log": {
        "loglevel": "error",
        "access": "/var/log/v2ray/access.log",
        "error": "/var/log/v2ray/error.log"
    },
    "inbounds": [{
        "port": 10086,
        "protocol": "vmess",
        "streamSettings": {
            "network": "ws",
            "wsSettings": {
                "path": "/ws"
            }
        },
        "tag": "proxy"
    }],
    "outbounds": [{ "protocol": "freedom" }]
}
```
日志报错如下
```
2020/06/11 11:06:26 [Error] V2ray-Poseidon: upload online ips err: invalid character '<' looking for beginning of value
2020/06/11 11:07:25 [Error] V2ray-Poseidon: upload user traffic err: invalid character '<' looking for beginning of value
```

**Comment by iddddg** [comment]
如果是接口的问题，能不能麻烦大佬给下接口地址和发送的数据格式呢？
感恩大佬

**Comment by ColetteContreras** [comment]
> 2020/06/11 11:06:26 [Error] V2ray-Poseidon: upload online ips err: invalid character '<' looking for beginning of value
2020/06/11 11:07:25 [Error] V2ray-Poseidon: upload user traffic err: invalid character '<' looking for beginning of value

这个报错说明是面板问题，后端把对应的数据发给面板的时候，面板报错了。

这是面板对应的接口代码，可以手动构造 http 请求调用一下，就知道是什么问题。https://github.com/Anankke/SSPanel-Uim/blob/dev/src/Controllers/Mod_Mu/UserController.php

**Comment by iddddg** [comment]
感谢,正在排查接口

**Comment by iddddg** [comment]
原因是好像脚本会GET /mod_mu/users/traffic接口,但是路由只有POST,会返回405错误,但是我的400模板不存在所以直接崩溃了

**Comment by iddddg** [comment]
原因是我nginx配置了http->https.
但是我在后端的panelUrl配置的是http://
在nginx日志中,显示POST /mod_mu/users/traffic 然后301到https的 /mod_mu/users/traffic,但是请求方式变成了GET,遂报405错误.
后端改为https已解决,谢谢大佬
