### ISSUE TITLE
请求援助，v2ray-poseidon后端对接v2board 面板

### ISSUE THREAD

**Issue by zhangxiangping5146** [ColetteContreras/v2ray-poseidon#88]
[root@hwsrv-734869 ws-tls]# dc logs
Attaching to v2ray-ws-tls
v2ray-ws-tls    | v2ray -config /etc/v2ray/config.json
v2ray-ws-tls    | V2Ray-Poseidon v1.5.7 (core: 4.23.4)
v2ray-ws-tls    | 2020/06/24 01:36:09 [Info] V2ray-Poseidon: updating geoip.dat and geosite.dat
v2ray-ws-tls    | 2020/06/24 01:36:09 [INFO] Caddy version: v1.0.4
v2ray-ws-tls    | Activating privacy features... 2020/06/24 01:36:09 [INFO][cache:0xc000031310] Started certificate maintenance routine
v2ray-ws-tls    | 
v2ray-ws-tls    | 
v2ray-ws-tls    | Your sites will be served over HTTPS automatically using Let's Encrypt.
v2ray-ws-tls    | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
v2ray-ws-tls    |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
v2ray-ws-tls    | Please enter your email address to signify agreement and to be notified
v2ray-ws-tls    | in case of issues. You can leave it blank, but we don't recommend it.
v2ray-ws-tls    |   Email address: 2020/06/24 01:36:09 [INFO][www.mrzhangfish.tk] Obtain certificate
v2ray-ws-tls    | 2020/06/24 01:36:09 [INFO][www.mrzhangfish.tk] Obtain: Waiting on rate limiter...
v2ray-ws-tls    | 2020/06/24 01:36:09 [INFO][www.mrzhangfish.tk] Obtain: Done waiting
v2ray-ws-tls    | 2020/06/24 01:36:09 [INFO] [www.mrzhangfish.tk] acme: Obtaining bundled SAN certificate
v2ray-ws-tls    | 2020/06/24 01:36:10 [Warning] V2ray-Poseidon: panel: V2board
v2ray-ws-tls    | 2020/06/24 01:36:10 [Warning] V2ray-Poseidon: node > check interval 60s
v2ray-ws-tls    | 2020/06/24 01:36:10 [Warning] V2ray-Poseidon: node > speed limit unlimited
v2ray-ws-tls    | 2020/06/24 01:36:10 [Warning] V2ray-Poseidon: user > max online ip count 0
v2ray-ws-tls    | 2020/06/24 01:36:10 [Warning] V2ray-Poseidon: user > speed limit unlimited
v2ray-ws-tls    | 2020/06/24 01:36:10 [INFO] [www.mrzhangfish.tk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5432836791
v2ray-ws-tls    | 2020/06/24 01:36:10 [INFO] [www.mrzhangfish.tk] acme: Could not find solver for: tls-alpn-01
v2ray-ws-tls    | 2020/06/24 01:36:10 [INFO] [www.mrzhangfish.tk] acme: Could not find solver for: http-01
v2ray-ws-tls    | 2020/06/24 01:36:10 [INFO] [www.mrzhangfish.tk] acme: use dns-01 solver
v2ray-ws-tls    | 2020/06/24 01:36:10 [INFO] [www.mrzhangfish.tk] acme: Preparing to solve DNS-01
v2ray-ws-tls    | 2020/06/24 01:36:10 [INFO] [www.mrzhangfish.tk] acme: Cleaning DNS-01 challenge
v2ray-ws-tls    | 2020/06/24 01:36:10 [WARN] [www.mrzhangfish.tk] acme: error cleaning up: cloudflare: unknown record ID for '_acme-challenge.www.mrzhangfish.tk.' 
v2ray-ws-tls    | 2020/06/24 01:36:10 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5432836791
v2ray-ws-tls    | 2020/06/24 01:36:11 [ERROR][www.mrzhangfish.tk] failed to obtain certificate: acme: Error -> One or more domains had a problem:
v2ray-ws-tls    | [www.mrzhangfish.tk] [www.mrzhangfish.tk] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials (attempt 1/3; challenge=dns-01)
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] [www.mrzhangfish.tk] acme: Obtaining bundled SAN certificate
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] [www.mrzhangfish.tk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5432837427
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] [www.mrzhangfish.tk] acme: Could not find solver for: tls-alpn-01
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] [www.mrzhangfish.tk] acme: Could not find solver for: http-01
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] [www.mrzhangfish.tk] acme: use dns-01 solver
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] [www.mrzhangfish.tk] acme: Preparing to solve DNS-01
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] [www.mrzhangfish.tk] acme: Cleaning DNS-01 challenge
v2ray-ws-tls    | 2020/06/24 01:36:12 [WARN] [www.mrzhangfish.tk] acme: error cleaning up: cloudflare: unknown record ID for '_acme-challenge.www.mrzhangfish.tk.' 
v2ray-ws-tls    | 2020/06/24 01:36:12 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5432837427
v2ray-ws-tls    | 2020/06/24 01:36:12 [ERROR][www.mrzhangfish.tk] failed to obtain certificate: acme: Error -> One or more domains had a problem:
v2ray-ws-tls    | [www.mrzhangfish.tk] [www.mrzhangfish.tk] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials (attempt 2/3; challenge=dns-01)
v2ray-ws-tls    | 2020/06/24 01:36:13 [INFO] [www.mrzhangfish.tk] acme: Obtaining bundled SAN certificate
v2ray-ws-tls    | 2020/06/24 01:36:13 [INFO] [www.mrzhangfish.tk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5432837756
v2ray-ws-tls    | 2020/06/24 01:36:13 [INFO] [www.mrzhangfish.tk] acme: Could not find solver for: tls-alpn-01
v2ray-ws-tls    | 2020/06/24 01:36:13 [INFO] [www.mrzhangfish.tk] acme: Could not find solver for: http-01
v2ray-ws-tls    | 2020/06/24 01:36:13 [INFO] [www.mrzhangfish.tk] acme: use dns-01 solver
v2ray-ws-tls    | 2020/06/24 01:36:13 [INFO] [www.mrzhangfish.tk] acme: Preparing to solve DNS-01
v2ray-ws-tls    | 2020/06/24 01:36:13 [INFO] [www.mrzhangfish.tk] acme: Cleaning DNS-01 challenge
v2ray-ws-tls    | 2020/06/24 01:36:13 [WARN] [www.mrzhangfish.tk] acme: error cleaning up: cloudflare: unknown record ID for '_acme-challenge.www.mrzhangfish.tk.' 
v2ray-ws-tls    | 2020/06/24 01:36:14 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5432837756
v2ray-ws-tls    | 2020/06/24 01:36:14 [ERROR][www.mrzhangfish.tk] failed to obtain certificate: acme: Error -> One or more domains had a problem:
v2ray-ws-tls    | [www.mrzhangfish.tk] [www.mrzhangfish.tk] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials (attempt 3/3; challenge=dns-01)
v2ray-ws-tls    | 2020/06/24 01:36:15 failed to obtain certificate: acme: Error -> One or more domains had a problem:
v2ray-ws-tls    | [www.mrzhangfish.tk] [www.mrzhangfish.tk] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials

我是docker 对接的波塞冬，v2board 版本 v2board v1.3 ,部署在centos 7 ，poseidon版本 v1.5.7 ，部署在centos 7。我是面板和后端分离部署的，在两台机器上。WebSocket-TLS 模式为例  

1？请问面板和poseidon 是需要部署在一台机上吗？还是可以分开部署？

2？最大的疑问就是，这个docker 对接，是否需要提前搭建好v2ray 节点服务，我刚开始都是用的一键脚本搭建的v2ray服务，然后poseidon再在这台机器上进行和面板对接，但是一直显示上面的错误，之后问过别人，说是不需要事先搭建v2ray服务，这个poseidon就是。从上面的报错信息可以看出来应该是证书获取不到的问题，所有的配置都没有错。但是看文档等等很多教程，并没有说到需要证书这一说，如果真的不需要搭建v2ray节点服务，那么poseidon 怎么去找/etc/v2ray/config.json 这个文件，我检查过很多次，无论怎么样弄，不搭建v2ray节点，是没有这个配置文件的，难道是需要自己手动去弄这个配置文件，文档里面也没有介绍。

3？还有一种对接方式，方式二 直接在系统中运行 v2ray-poseidon，我今天确实对接成功了，这个/etc/v2ray/config.json 文件别人确实是手动拉下来的，而且是手动获取的证书。不知道第一种说的docker对接是否也是这样做，但是实际上我这样做了，仍然报告上面的错误。

wget -O /etc/v2ray/config.json https://raw.githubusercontent.com/ColetteContreras/v2ray-poseidon/master/docker/v2board/tcp/config.json

4，下面是我的v2board-poseidon 的配置文件

/root/v2ray-poseidon/docker/v2board/ws-tls/docker-compose.xml

version: '3'

services:
  v2ray-ws-tls:
    image: v2cc/poseidon
    container_name: v2ray-ws-tls
    restart: always
    ports:
      # 使用 Caddy 生成 TLS 证书，所以后面的是 443
      - "443:443"
    volumes:
      - ./config.json:/etc/v2ray/config.json
    logging:
      driver: "json-file"
      options:
        max-size: 2g
    environment:
      - USE_CADDY_TLS=true

      # 使用 cloudflare DNS 验证
      - CF_API_EMAIL=1907028118@qq.com
      - CF_API_KEY=d26e28981654fd13b16bc6baf0225747374bc
      # 使用 namesilo DNS 验证
      #- NAMESILO_API_KEY=
      # 使用 namecheap DNS 验证
      #- NAMECHEAP_API_USER=
      #- NAMECHEAP_API_KEY=
    # 使用哪个把哪个前面的井号去掉，其它的全部注释
    command: tls cloudflare www.mrzhangfish.tk
    #command: tls namesilo your.domain
    #command: tls namecheap your.domain

/root/v2ray-poseidon/docker/v2board/ws-tls/config.json

{
  "poseidon": {
    "panel": "v2board",         // 这一行必须存在，且不能更改
    "nodeId": 1,                // 你的节点 ID 和 v2board 里的一致
    "checkRate": 60,            // 每隔多长时间同步一次配置文件、用户、上报服务器信息
    "webapi": "https://www.mrzhangfish.ml",// v2board 的域名信息
    "token": "zhangxiangping5146",   // v2board 和 v2ray-poseidon 的通信密钥

    "speedLimit": 0, // 节点限速 单位 字节/s 0 表示不限速
    "user": {
      "maxOnlineIPCount": 0,  // 用户同时在线 IP 数限制 0 表示不限制
      "speedLimit": 0         // 用户限速 单位 字节/s 0 表示不限速
    }
  }
}
请大佬作者指点迷津，帮助大家少走弯路，再次感谢大佬。

**Comment by ColetteContreras** [comment]
> v2ray-ws-tls | [www.mrzhangfish.tk] [www.mrzhangfish.tk] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials (attempt 2/3; challenge=dns-01)

这个错误已经报的非常明确了，认证信息错误，这是自动生成 TLS 的时候需要的。

### Cloudflare key获取
CloudFlare-右上角头像-我的个人资料-API令牌-Global API Key-查看

详细文档：https://poseidon-gfw.cc/shi-yong-v2ray-poseidon/v2ray-poseidon-with-v2board

> 1？请问面板和poseidon 是需要部署在一台机上吗？还是可以分开部署？

先搞明白"面板"是做什么的，面板是一个用户管理系统、在线商品销售及引用用户使用产品的一整套系统
其次可以再去了解 v2ray，它是一个代理工具，能配置的就是一个配置文件，但是怎么把面板购买了产品上的用户自动同步到 v2ray 里面，这就是 V2Ray-Poseidon 所做的事情，它是一个桥梁，将面板和 v2ray 连接在一起。

**面板和 V2Ray-Poseidon 不需要在一台机器上**

> 2？最大的疑问就是，这个docker 对接，是否需要提前搭建好v2ray 节点服务？

不需要， V2Ray-Poseidon 就是一直增强版的 v2ray，它包含了所有的 v2ray 的功能

> 3？还有一种对接方式，方式二 直接在系统中运行 v2ray-poseidon，我今天确实对接成功了，这个/etc/v2ray/config.json 文件别人确实是手动拉下来的，而且是手动获取的证书。不知道第一种说的docker对接是否也是这样做，但是实际上我这样做了，仍然报告上面的错误。

有错误就针对错误，做修改即可，无非两种错误：i. 使用错误 ii. 软件本身错误（这个可能性不大，因为本项目开源版本运行了快2年了，bug 基本都找完了

> 4

私密信息记得打码

**Comment by zhangxiangping5146** [comment]
您好，我的cf api key 是正确的，而且我已经操作过很几次，域名也换过了，还是同样的错误，请问是哪里有问题呢？我这个是. ml 免费的域名。请问docker 对接/ etc / v2ray /下面的config.json 配置文件在哪里？

**Comment by ColetteContreras** [comment]
从你的这个说明看不出问题，但报错确实就是 cf 的信息错误，实在不行加群，找大佬帮忙，应该很简单 https://t.me/v2ray_poseidon

**Comment by fat00119** [comment]
. ml 免费的域名
免费域名不能用cf的api了

**Comment by zhangxiangping5146** [comment]
> 从你的这个说明看不出问题，但报错确实就是 cf 的信息错误，实在不行加群，找大佬帮忙，应该很简单 https://t.me/v2ray_poseidon

好的，谢谢大佬的回复哦。

**Comment by zhangxiangping5146** [comment]
> . ml 免费的域名
> 免费域名不能用cf的api了

可是其他的脚本申请证书的时候都没有问题啊，是.ml免费的域名的不能申请到acme的证书了吗？

**Comment by ColetteContreras** [comment]
> . ml 免费的域名
> 免费域名不能用cf的api了

原来是这样啊，查了下确实：这几个免费的域名都没法使用 CF 的 API 了：.cf, .ga, .gq, .ml or .tk

https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228

> 可是其他的脚本申请证书的时候都没有问题啊，是.ml免费的域名的不能申请到acme的证书了吗？

因为 V2Ray-Poseidon 申请 TLS 用的 dns 认证的方式，而不是 80 或 443 端口的方式。你可以用 acme 自己申请，然后配置文件使用对应的证书

**Comment by zhangxiangping5146** [comment]
> > . ml 免费的域名
> > 免费域名不能用cf的api了
> 
> 原来是这样啊，查了下确实：这几个免费的域名都没法使用 CF 的 API 了：.cf, .ga, .gq, .ml or .tk
> 
> https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228
> 
> > 可是其他的脚本申请证书的时候都没有问题啊，是.ml免费的域名的不能申请到acme的证书了吗？
> 
> 因为 V2Ray-Poseidon 申请 TLS 用的 dns 认证的方式，而不是 80 或 443 端口的方式。你可以用 acme 自己申请，然后配置文件使用对应的证书
> 
> 

好的，谢谢哦，我再试试看。
