### ISSUE TITLE
user->inboundTag 支持数组吗？

### ISSUE THREAD

**Issue by evilkong** [ColetteContreras/v2ray-poseidon#93]
rt，范例只是一个字符串，是否支持数组，然后支持往多个inbounds引入用户？

测试了下报json解释错误，是不是有别的方法实现呢？

**Comment by ColetteContreras** [comment]
有的，专门支持了，就是用的人少就没写出来， `"inboundTag": "inbound1,inbound2",` 英文逗号隔开，逗号前后不要有任何空白字符。

**Comment by evilkong** [comment]
感谢老大指导

**Comment by evilkong** [comment]
尝试了下报错：
`
...
 [Warning] V2ray-Poseidon: SSRPanel mysql
[Error] V2ray-Poseidon: get panelcheck config > Miss an inbound tagged proxy,proxymess
...
`

其中配置如下：
`
...
"poseidon": {
    "panel": "ssrpanel",
    "license_key": "",
    "nodeId": 9,
    "checkRate": 60,
    "user": {
      "inboundTag":"proxy,proxymess", 
      "level": 0,
      "alterId": 129,
      "security": "none"
    }
...
`

版本是v1.5.8
之前我使用的是 V2Ray 4.9 (Po) Custom

貌似不兼容，然后升级了报错。使用单个时正常。不过后面的数据库貌似要升级（缺少用户字段）。

**Comment by ColetteContreras** [comment]
这种你需要使用本地的配置了，因为默认的 inbound 就一个 tag 为 proxy，你现在指定两个，那哪来的第二个。

所以需要使用 useLocalProxy ，这时所有的配置文件都需要你自己写，可以参考 https://github.com/ColetteContreras/v2ray-poseidon/blob/master/docker/ssrpanel/ws/config.json
