### ISSUE TITLE
[Error] V2ray-Poseidon: Could not match your host ip

### ISSUE THREAD

**Issue by 911211606** [ColetteContreras/v2ray-poseidon#96]
NSLookup over tls:  [172.64.94.113]
NSLookup [172.64.92.24]
2020/10/22 21:15:39 [Error] V2ray-Poseidon: Could not match your host ip xx.com.

为什么无法匹配ip？都是一键脚本啊

**Comment by ColetteContreras** [comment]
可以把系统的 dns 设置成 8.8.8.8，因为你通过系统直接解析到的ip为172.64.92.24，而使用 DoT 的方式获取到的是 172.64.94.113，所以就不匹配了

**Comment by ColetteContreras** [comment]
可以更新到最新版 v1.7.0，使用的其它的方式来验证，不会出现这个问题了
