### ISSUE TITLE
v2board 新增的alterId 选项 Poseidon 配置文件不支持

### ISSUE THREAD

**Issue by yywudi** [ColetteContreras/v2ray-poseidon#97]
v2board dev branch 更新到最新，在v2board 前端服务器节点配置中增加了alterId选项。
后端v2ray-poseidon 最新的1.7.0，即使在 “user" 中已有（或添加）”alterId“: 2, （前端alterId也已经从默认的1改成了2） 还是会一直报invalid user而无法使用。
配置

> {
  "poseidon": {
    "panel": "v2board",
    "license_key": "",
    "nodeId": 11,
    "checkRate": 60,
    "webapi": "https://xxxxxxx.xxx", // SSPanel 面板地址
    "token": "xxxxxxx",              // SSPanel 面板的配置文件中的 muKey 的值
    "speedLimit":0,
    "user": {
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 2,
      "security": "none"
    }
  },
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [{
    "port": 10247,
    "protocol": "vmess",
    "tag": "proxy"
  }],
  "outbounds": [{
    "protocol": "freedom"
  }]
}

**Comment by ColetteContreras** [comment]
感谢反馈，已经给 V2Board 提了 PR，等合并后即可正常使用 https://github.com/v2board/v2board/pull/343

**Comment by yywudi** [comment]
修改 经测试已经可以了。
