### ISSUE TITLE
v2board面板配置文件增加outbounds，log，inbounds

### ISSUE THREAD

**Issue by 1978245715** [ColetteContreras/v2ray-poseidon#99]
请问是否考虑这样的配置，我看最新版v2ray-poseidon配置文件中，SSPanel里有这个功能，但是我使用在v2board 后，配置不生效，journalctl查看也是null值的~

**Comment by ColetteContreras** [comment]
文档在这里 [V2Ray 高玩：自定义 V2Ray 配置文件](https://poseidon-gfw.cc/za-xiang/use-local-config)
